# Generated by Django 5.2.14 on 2026-08-27 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_servicepage_extra_content'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeteorologicalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('name', models.CharField(max_length=255, verbose_name='Service name')),
                ('acronym', models.CharField(blank=True, max_length=30, verbose_name='Acronym')),
                ('website_url', models.URLField(help_text='The official website opened when a visitor selects the card.', max_length=500, verbose_name='Website URL')),
                ('logo_source_url', models.URLField(blank=True, help_text='Optional external fallback used until a logo is uploaded.', max_length=500, verbose_name='Fallback logo URL')),
                ('wmo_member_id', models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Visible on the directory')),
                ('logo', models.ForeignKey(blank=True, help_text='Upload the official service logo. A sourced fallback is used when empty.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Meteorological Service',
                'verbose_name_plural': 'Meteorological Services',
                'ordering': ('order', 'country', 'name'),
            },
        ),
    ]
