# Generated by Django 5.2.14 on 2026-09-01 09:40

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0017_servicepage_sector_heading_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicepage",
            name="service_sectors",
            field=wagtail.fields.StreamField(
                [("sector", 24)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"help_text": "Short URL-safe name, for example agriculture or health.", "max_length": 60}),
                    1: ("wagtail.blocks.CharBlock", (), {"max_length": 120}),
                    2: ("wagtailiconchooser.blocks.IconChooserBlock", (), {"default": "globe", "required": False}),
                    3: ("wagtail.blocks.TextBlock", (), {}),
                    4: ("wagtail.blocks.RichTextBlock", (), {"features": ["bold", "ul", "ol", "link", "superscript", "subscript", "h2", "h3", "h4"], "label": "Aim and approach", "required": False}),
                    5: ("wagtail.blocks.CharBlock", (), {"max_length": 160}),
                    6: ("wagtail.blocks.ListBlock", (5,), {"label": "Key climate risks", "required": False}),
                    7: ("wagtail.blocks.CharBlock", (), {"max_length": 200}),
                    8: ("wagtail.blocks.ListBlock", (7,), {"label": "Climate services and information needs", "required": False}),
                    9: ("wagtail.blocks.ListBlock", (7,), {"label": "Activities and expected outcomes", "required": False}),
                    10: ("wagtail.blocks.ListBlock", (7,), {"label": "Participating institutions", "required": False}),
                    11: ("wagtail.blocks.RichTextBlock", (), {"features": ["bold", "ul", "ol", "link", "superscript", "subscript", "h2", "h3", "h4"], "help_text": "Governance, chair, secretariat and meeting arrangements stated in the TOR.", "label": "Rules of procedure", "required": False}),
                    12: ("wagtail.blocks.ListBlock", (7,), {"label": "Platform composition", "required": False}),
                    13: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    14: ("wagtail.blocks.URLBlock", (), {"max_length": 500}),
                    15: ("wagtail.blocks.CharBlock", (), {"default": "Open resource", "max_length": 40}),
                    16: ("wagtail.blocks.StructBlock", [[("title", 5), ("description", 13), ("url", 14), ("link_label", 15)]], {}),
                    17: ("wagtail.blocks.ListBlock", (16,), {"label": "Terms of Reference documents", "required": False}),
                    18: ("wagtail.blocks.PageChooserBlock", (), {"page_type": ["products.ProductPage"]}),
                    19: ("wagtail.blocks.ListBlock", (18,), {"label": "Related products", "required": False}),
                    20: ("wagtail.blocks.ListBlock", (16,), {"label": "External tools and resources", "required": False}),
                    21: ("wagtail.blocks.URLBlock", (), {"max_length": 500, "required": False}),
                    22: ("wagtail.blocks.StructBlock", [[("title", 7), ("details", 13), ("url", 21)]], {}),
                    23: ("wagtail.blocks.ListBlock", (22,), {"label": "Meetings and activities", "required": False}),
                    24: ("wagtail.blocks.StructBlock", [[("anchor", 0), ("title", 1), ("icon", 2), ("summary", 3), ("aim", 4), ("risks", 6), ("climate_services", 8), ("activities", 9), ("institutions", 10), ("rules_of_procedure", 11), ("platform_composition", 12), ("tor_documents", 17), ("products", 19), ("external_tools", 20), ("meetings", 23)]], {}),
                },
                null=True,
                verbose_name="Service sectors",
            ),
        ),
    ]
