# Generated by Django 5.2.14 on 2026-09-02 08:22

import django.db.models.deletion
import wagtail.fields
import wagtailcache.cache
import wagtailmetadata.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_alter_servicepage_introduction_title'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnTheJobTrainingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('banner_title', models.CharField(max_length=255, verbose_name='Banner Title')),
                ('banner_subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Banner Subtitle')),
                ('call_to_action_button_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Call to action button text')),
                ('introduction_title', models.CharField(help_text='Introduction section title', max_length=100, verbose_name='Introduction Title')),
                ('introduction_text', wagtail.fields.RichTextField(help_text='Introduction section description', verbose_name='Introduction text')),
                ('introduction_button_text', models.CharField(blank=True, max_length=20, null=True, verbose_name='Introduction button text')),
                ('introduction_button_link_external', models.URLField(blank=True, help_text='External Link if applicable. Ignored if internal page above is chosen', null=True)),
                ('objectives', wagtail.fields.RichTextField()),
                ('eligibility', wagtail.fields.RichTextField()),
                ('duration', models.CharField(default='2-6 months', max_length=120)),
                ('location', models.CharField(default='ACMAD Headquarters, Niamey, Niger', max_length=160)),
                ('languages', models.CharField(default='English and French', max_length=120)),
                ('benefits', wagtail.fields.RichTextField()),
                ('training_modules', wagtail.fields.StreamField([('module', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 160}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1)]], {})})),
                ('application_introduction', wagtail.fields.RichTextField(blank=True)),
                ('application_steps', wagtail.fields.StreamField([('step', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'ul', 'ol', 'link', 'superscript', 'subscript', 'h2', 'h3', 'h4']}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1)]], {})})),
                ('application_email', models.EmailField(default='secretariat@acmad.org', max_length=254)),
                ('reports_introduction', wagtail.fields.RichTextField(blank=True)),
                ('visitor_reports', wagtail.fields.StreamField([('report', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 180}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 160, 'required': False}), 3: ('wagtail.blocks.DateBlock', (), {'required': False}), 4: ('wagtail.blocks.TextBlock', (), {'required': False}), 5: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': True}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('visitor_name', 1), ('country_or_institution', 2), ('date', 3), ('summary', 4), ('document', 5)]], {})})),
                ('testimonials', wagtail.fields.StreamField([('testimony', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 160, 'required': False}), 2: ('wagtail.blocks.TextBlock', (), {}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('name', 0), ('organisation', 1), ('quote', 2), ('photo', 3)]], {})})),
                ('gallery', wagtail.fields.StreamField([('item', 4)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('image', 'Image'), ('video', 'Video')]}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'YouTube or Vimeo URL', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 180, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('media_type', 0), ('image', 1), ('video_url', 2), ('caption', 3)]], {})})),
                ('accommodation_introduction', wagtail.fields.RichTextField(blank=True)),
                ('accommodation_options', wagtail.fields.StreamField([('accommodation', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 160}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 220, 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('name', 0), ('description', 1), ('address', 2), ('website', 3), ('contact', 4), ('image', 5)]], {})})),
                ('banner_image', models.ForeignKey(blank=True, help_text='A high quality banner image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Banner Image')),
                ('brochure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document')),
                ('call_to_action_related_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Call to action related page')),
                ('introduction_button_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Introduction button link')),
                ('introduction_image', models.ForeignKey(blank=True, help_text='A high quality image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Introduction Image')),
                ('search_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Search image')),
            ],
            options={
                'verbose_name': 'On-the-Job Training Page',
            },
            bases=(wagtailmetadata.models.WagtailImageMetadataMixin, 'wagtailcore.page', models.Model, wagtailcache.cache.WagtailCacheMixin),
        ),
    ]
