# Generated by Django 5.2.14 on 2026-09-03 09:22

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_onthejobtrainingpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='onthejobtrainingpage',
            name='participant_map_date_from',
            field=models.DateField(blank=True, help_text='Optional. Only count engagements active on or after this date.', null=True, verbose_name='From date'),
        ),
        migrations.AddField(
            model_name='onthejobtrainingpage',
            name='participant_map_date_to',
            field=models.DateField(blank=True, help_text='Optional. Only count engagements that started on or before this date.', null=True, verbose_name='To date'),
        ),
        migrations.AddField(
            model_name='onthejobtrainingpage',
            name='participant_map_heading',
            field=models.CharField(default='Where our participants come from', max_length=120, verbose_name='Participant map heading'),
        ),
        migrations.AddField(
            model_name='onthejobtrainingpage',
            name='participant_map_introduction',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Participant map introduction'),
        ),
        migrations.AddField(
            model_name='onthejobtrainingpage',
            name='participant_map_scope',
            field=models.CharField(choices=[('both', 'On-the-job training and secondment'), ('ojt', 'On-the-job training only'), ('secondment', 'Secondment only')], default='both', max_length=20, verbose_name='Participants to include'),
        ),
        migrations.AddField(
            model_name='onthejobtrainingpage',
            name='show_participant_map',
            field=models.BooleanField(default=False, help_text='Display an Africa choropleth of participants per country, built from the Capacity Building Participants register.', verbose_name='Show participant map'),
        ),
    ]
