# Generated by Django 5.2.14 on 2026-09-08 10:59

import django.db.models.deletion
import wagtail.fields
import wagtailcache.cache
import wagtailmetadata.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_onthejobtrainingpage_participant_map_date_from_and_more'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RCCDataServicesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('banner_title', models.CharField(max_length=255, verbose_name='Banner Title')),
                ('banner_subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Banner Subtitle')),
                ('call_to_action_button_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Call to action button text')),
                ('introduction_title', models.CharField(help_text='Introduction section title', max_length=100, verbose_name='Introduction Title')),
                ('introduction_text', wagtail.fields.RichTextField(help_text='Introduction section description', verbose_name='Introduction text')),
                ('introduction_button_text', models.CharField(blank=True, max_length=20, null=True, verbose_name='Introduction button text')),
                ('introduction_button_link_external', models.URLField(blank=True, help_text='External Link if applicable. Ignored if internal page above is chosen', null=True)),
                ('catalogue_notice', wagtail.fields.RichTextField(blank=True, help_text='Explain access restrictions, verification dates and archive status.', verbose_name='Catalogue access notice')),
                ('data_groups', wagtail.fields.StreamField([('group', 13)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Short URL-safe name, for example observations or models.', 'max_length': 60}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 140}), 2: ('wagtail.blocks.TextBlock', (), {}), 3: ('wagtailiconchooser.blocks.IconChooserBlock', (), {'default': 'database', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 180}), 5: ('wagtail.blocks.TextBlock', (), {'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'For example NetCDF, CSV, PNG or catalogue.', 'max_length': 100, 'required': False}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('open', 'Open access'), ('external', 'External login required'), ('request', 'Available by request'), ('archive', 'Legacy or archive')]}), 9: ('wagtail.blocks.URLBlock', (), {'max_length': 500, 'required': False}), 10: ('wagtail.blocks.DateBlock', (), {'required': False}), 11: ('wagtail.blocks.StructBlock', [[('title', 4), ('description', 5), ('coverage', 6), ('formats', 7), ('access_type', 8), ('access_url', 9), ('source', 6), ('last_verified', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'label': 'Datasets and services'}), 13: ('wagtail.blocks.StructBlock', [[('anchor', 0), ('title', 1), ('summary', 2), ('icon', 3), ('datasets', 12)]], {})}, verbose_name='Data service groups')),
                ('banner_image', models.ForeignKey(blank=True, help_text='A high quality banner image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Banner Image')),
                ('call_to_action_related_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Call to action related page')),
                ('data_request_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Data request page')),
                ('introduction_button_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Introduction button link')),
                ('introduction_image', models.ForeignKey(blank=True, help_text='A high quality image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Introduction Image')),
                ('search_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Search image')),
            ],
            options={
                'verbose_name': 'RCC Data Services Page',
            },
            bases=(wagtailmetadata.models.WagtailImageMetadataMixin, 'wagtailcore.page', models.Model, wagtailcache.cache.WagtailCacheMixin),
        ),
    ]
