# Generated by Django 5.2.14 on 2026-09-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_rccclimateproductspage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rccclimateproductspage',
            name='introduction_title',
            field=models.CharField(blank=True, default='', help_text='Optional introduction section title', max_length=100, verbose_name='Introduction Title'),
        ),
    ]
