# Generated by Django 5.2.14 on 2026-09-14 15:41

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_alter_rccclimateproductspage_introduction_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rccclimateproductspage',
            name='introduction_text',
            field=wagtail.fields.RichTextField(blank=True, default='', help_text='Optional introduction section description', verbose_name='Introduction text'),
        ),
    ]
