# Generated by Django 5.2.14 on 2026-09-15 08:28

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_alter_rccclimateproductspage_introduction_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='activities',
            field=wagtail.fields.StreamField([('activity', 8)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('image', 'Image'), ('chart', 'Chart'), ('video', 'Video'), ('imageofchange', 'Image of Change')]}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'A URL that returns Highcharts.js configuration, including the data', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {}), 4: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'ul', 'ol', 'link', 'superscript', 'subscript', 'h2', 'h3', 'h4'], 'label': 'Description'}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 15, 'required': False}), 6: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Action Link Internal', 'required': False}), 7: ('wagtail.blocks.URLBlock', (), {'help_text': 'An external link to a detailed resource on the internet.If provided, the internal link will be ignored', 'max_length': 400, 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('figure_type', 0), ('image', 1), ('chart_config_url', 2), ('title', 3), ('text', 4), ('action_link_text', 5), ('action_link', 6), ('action_link_external', 7)]], {})}, null=True, verbose_name='Activities'),
        ),
    ]
