# Generated by Django 5.2.14 on 2026-09-15 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_servicepage_activities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='activities',
        ),
    ]
