# Generated by Django 5.2.14 on 2026-09-15 09:41

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_remove_servicepage_activities'),
    ]

    operations = [
        migrations.CreateModel(
            name='RCCDatasetAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('summary', models.TextField(blank=True)),
                ('station', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('longitude', models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('source_url', models.URLField(blank=True, max_length=700)),
                ('object_name', models.CharField(blank=True, max_length=500)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('coverage_start', models.DateField(blank=True, null=True)),
                ('coverage_end', models.DateField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'RCC dataset',
                'verbose_name_plural': 'RCC datasets',
                'ordering': ('title',),
            },
        ),
        migrations.AlterField(
            model_name='rccdataservicespage',
            name='data_groups',
            field=wagtail.fields.StreamField([('group', 14)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Short URL-safe name, for example observations or models.', 'max_length': 60}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 140}), 2: ('wagtail.blocks.TextBlock', (), {}), 3: ('wagtailiconchooser.blocks.IconChooserBlock', (), {'default': 'database', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 180}), 5: ('wagtail.blocks.TextBlock', (), {'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'For example NetCDF, CSV, PNG or catalogue.', 'max_length': 100, 'required': False}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('open', 'Open access'), ('external', 'External login required'), ('request', 'Available by request'), ('archive', 'Legacy or archive')]}), 9: ('wagtail.blocks.URLBlock', (), {'max_length': 500, 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Key for an RCC-hosted dataset page. When set, this replaces the external access URL.', 'max_length': 80, 'required': False}), 11: ('wagtail.blocks.DateBlock', (), {'required': False}), 12: ('wagtail.blocks.StructBlock', [[('title', 4), ('description', 5), ('coverage', 6), ('formats', 7), ('access_type', 8), ('access_url', 9), ('local_dataset_key', 10), ('source', 6), ('last_verified', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'label': 'Datasets and services'}), 14: ('wagtail.blocks.StructBlock', [[('anchor', 0), ('title', 1), ('summary', 2), ('icon', 3), ('datasets', 13)]], {})}, verbose_name='Data service groups'),
        ),
    ]
