# Generated by Django 5.2.14 on 2026-09-16 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0032_arc2_singleton_schema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RCCCPCImportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.CharField(default='cpc-unified', editable=False, max_length=20, unique=True)),
                ('catalogue_url', models.URLField(default='http://sgbd.acmad.org:8080/thredds/catalog/ACMAD/CDD/climatedataservice/Synoptic_Daily_CPC_Unified_Data/catalog.xml', max_length=700)),
                ('enabled', models.BooleanField(default=False)),
                ('interval_hours', models.PositiveSmallIntegerField(default=24)),
                ('import_all_stations', models.BooleanField(default=False)),
                ('discovered_countries', models.JSONField(blank=True, default=list)),
                ('selected_stations', models.JSONField(blank=True, default=list)),
                ('discovered_stations', models.JSONField(blank=True, default=list)),
                ('discovered_at', models.DateTimeField(blank=True, null=True)),
                ('discovery_error', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RCCCPCImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('partial', 'Partially succeeded'), ('failed', 'Failed')], default='queued', max_length=12)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled')], max_length=12)),
                ('stations', models.JSONField(default=list)),
                ('country', models.CharField(default='', max_length=80)),
                ('catalogue_url', models.URLField(blank=True, max_length=700)),
                ('import_all_stations', models.BooleanField(default=False)),
                ('results', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='services.rcccpcimportconfig')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
