# Generated by Django 5.2.14 on 2026-09-16 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0033_rcccpcimportconfig_rcccpcimportrun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RCCSeasonalMapAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=80, unique=True)),
                ('season', models.CharField(max_length=3)),
                ('variant', models.CharField(max_length=10)),
                ('source_url', models.URLField(max_length=700)),
                ('object_name', models.CharField(max_length=500)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('size_bytes', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('synced_at', models.DateTimeField()),
            ],
            options={
                'ordering': ('filename',),
            },
        ),
        migrations.CreateModel(
            name='RCCSeasonalMapImportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.CharField(default='seasonal-maps', editable=False, max_length=30, unique=True)),
                ('catalogue_url', models.URLField(default='http://sgbd.acmad.org:8080/thredds/catalog/ACMAD/CDD/statisticalanalysis/Precipitation/Gridded_Observation/catalog.xml', max_length=700)),
                ('enabled', models.BooleanField(default=False)),
                ('interval_hours', models.PositiveSmallIntegerField(default=168)),
                ('import_all_maps', models.BooleanField(default=False)),
                ('discovered_maps', models.JSONField(blank=True, default=list)),
                ('selected_maps', models.JSONField(blank=True, default=list)),
                ('discovered_at', models.DateTimeField(blank=True, null=True)),
                ('discovery_error', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RCCSeasonalMapImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('partial', 'Partially succeeded'), ('failed', 'Failed')], default='queued', max_length=12)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled')], max_length=12)),
                ('maps', models.JSONField(default=list)),
                ('catalogue_url', models.URLField(max_length=700)),
                ('import_all_maps', models.BooleanField(default=False)),
                ('results', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='services.rccseasonalmapimportconfig')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
