# Generated by Django 5.2.14 on 2026-09-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0036_station_import_cancellation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RCCClimateIndexAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_index', models.PositiveSmallIntegerField(unique=True)),
                ('title', models.CharField(max_length=240)),
                ('scope', models.CharField(max_length=30)),
                ('source_url', models.URLField(max_length=700)),
                ('object_name', models.CharField(max_length=500)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('size_bytes', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('synced_at', models.DateTimeField()),
            ],
            options={
                'ordering': ('legacy_index',),
            },
        ),
    ]
