# Generated by Django 5.2.14 on 2026-09-21 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_existing_versions(apps, schema_editor):
    Asset = apps.get_model("services", "RCCClimateIndexAsset")
    Version = apps.get_model("services", "RCCClimateIndexVersion")
    for asset in Asset.objects.exclude(object_name="").exclude(checksum_sha256=""):
        Version.objects.get_or_create(
            asset_id=asset.pk,
            checksum_sha256=asset.checksum_sha256,
            defaults={
                "source_url": asset.source_url,
                "object_name": asset.object_name,
                "size_bytes": asset.size_bytes,
                "width": asset.width,
                "height": asset.height,
                "synced_at": asset.synced_at,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0037_rccclimateindexasset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RCCClimateIndexImportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.CharField(default='climate-indices', editable=False, max_length=30, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('interval_hours', models.PositiveSmallIntegerField(default=168)),
            ],
        ),
        migrations.AddField(
            model_name='rccclimateindexasset',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rccclimateindexasset',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rccclimateindexasset',
            name='last_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rccclimateindexasset',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rccclimateindexasset',
            name='period',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='rccclimateindexasset',
            name='checksum_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='rccclimateindexasset',
            name='height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rccclimateindexasset',
            name='object_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='rccclimateindexasset',
            name='size_bytes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rccclimateindexasset',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rccclimateindexasset',
            name='width',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RCCClimateIndexImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('partial', 'Partially succeeded'), ('failed', 'Failed')], default='queued', max_length=12)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled')], max_length=12)),
                ('asset_ids', models.JSONField(default=list)),
                ('results', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='services.rccclimateindeximportconfig')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RCCClimateIndexVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=700)),
                ('object_name', models.CharField(max_length=500)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('size_bytes', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('synced_at', models.DateTimeField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='services.rccclimateindexasset')),
            ],
            options={
                'ordering': ('-synced_at',),
                'constraints': [models.UniqueConstraint(fields=('asset', 'checksum_sha256'), name='unique_climate_index_version')],
            },
        ),
        migrations.RunPython(preserve_existing_versions, migrations.RunPython.noop),
    ]
