# Generated by Django 5.2.14 on 2026-09-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0039_rccclimatemonitoringpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RCCReferenceClimatology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=3)),
                ('country', models.CharField(max_length=100)),
                ('station_id', models.CharField(max_length=20)),
                ('station_name', models.CharField(max_length=120)),
                ('period_start', models.PositiveSmallIntegerField()),
                ('period_end', models.PositiveSmallIntegerField()),
                ('monthly_data', models.JSONField(default=list)),
                ('source_url', models.URLField(max_length=700)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RCC reference climatology',
                'verbose_name_plural': 'RCC reference climatologies',
                'ordering': ('country', 'station_name', 'period_start'),
                'constraints': [models.UniqueConstraint(fields=('country_code', 'station_id', 'period_start', 'period_end'), name='unique_rcc_station_climatology_period')],
            },
        ),
    ]
