# Generated by Django 5.2.14 on 2026-09-24 08:25

import django.db.models.deletion
import wagtail.fields
import wagtailcache.cache
import wagtailmetadata.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0041_rcclongrangeforecastingpage'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RCCConsensusForumPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('banner_title', models.CharField(max_length=255, verbose_name='Banner Title')),
                ('banner_subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Banner Subtitle')),
                ('call_to_action_button_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Call to action button text')),
                ('forum_code', models.CharField(help_text='For example PRESAC, MEDCOF or ACCOF.', max_length=30, verbose_name='Forum acronym')),
                ('region', models.CharField(max_length=180)),
                ('target_season', models.CharField(blank=True, max_length=180)),
                ('summary', models.TextField(help_text='Short description used on the forum directory card.', max_length=500)),
                ('overview', wagtail.fields.RichTextField()),
                ('geographic_coverage', wagtail.fields.RichTextField(blank=True)),
                ('climate_drivers', wagtail.fields.RichTextField(blank=True)),
                ('climate_hazards', wagtail.fields.RichTextField(blank=True)),
                ('consensus_method', wagtail.fields.RichTextField(blank=True, verbose_name='How the consensus is developed')),
                ('user_involvement', wagtail.fields.RichTextField(blank=True)),
                ('development_priorities', wagtail.fields.RichTextField(blank=True)),
                ('archive_codes', models.CharField(blank=True, help_text='Comma-separated acronyms used to associate documents from the Consensus Statements product archive. Defaults to the forum acronym.', max_length=120)),
                ('photos', wagtail.fields.StreamField([('photo', 3)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 220, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 160, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 0), ('caption', 1), ('credit', 2)]], {})}, verbose_name='Photo gallery')),
                ('attached_documents', wagtail.fields.StreamField([('document', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 220, 'required': False}), 1: ('wagtail.blocks.DateBlock', (), {'required': False}), 2: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': True}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('date', 1), ('document', 2)]], {})}, verbose_name='Additional forum documents')),
                ('banner_image', models.ForeignKey(blank=True, help_text='A high quality banner image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Banner Image')),
                ('call_to_action_related_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Call to action related page')),
                ('search_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Search image')),
            ],
            options={
                'verbose_name': 'RCC Consensus Forum Page',
            },
            bases=(wagtailmetadata.models.WagtailImageMetadataMixin, 'wagtailcore.page', models.Model, wagtailcache.cache.WagtailCacheMixin),
        ),
    ]
