# Generated by Django 5.2.14 on 2026-09-24 09:39

import django.db.models.deletion
import wagtail.fields
import wagtailcache.cache
import wagtailmetadata.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0042_rccconsensusforumpage'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RCCTrainingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('banner_title', models.CharField(max_length=255, verbose_name='Banner Title')),
                ('banner_subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Banner Subtitle')),
                ('call_to_action_button_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Call to action button text')),
                ('introduction_title', models.CharField(help_text='Introduction section title', max_length=100, verbose_name='Introduction Title')),
                ('introduction_text', wagtail.fields.RichTextField(help_text='Introduction section description', verbose_name='Introduction text')),
                ('introduction_button_text', models.CharField(blank=True, max_length=20, null=True, verbose_name='Introduction button text')),
                ('introduction_button_link_external', models.URLField(blank=True, help_text='External Link if applicable. Ignored if internal page above is chosen', null=True)),
                ('focus_areas', wagtail.fields.StreamField([('area', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 160}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1)]], {})}, verbose_name='RCC training focus areas')),
                ('programmes', wagtail.fields.StreamField([('programme', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 180}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtailiconchooser.blocks.IconChooserBlock', (), {'default': 'graduation-cap', 'required': False}), 3: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'max_length': 500, 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Explore programme', 'max_length': 60, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('icon', 2), ('page', 3), ('external_url', 4), ('link_label', 5)]], {})}, verbose_name='Programmes and activities')),
                ('methodology_groups', wagtail.fields.StreamField([('group', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Short URL-safe name, for example data-rescue.', 'max_length': 60}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 180}), 2: ('wagtail.blocks.TextBlock', (), {'required': False}), 3: ('wagtailiconchooser.blocks.IconChooserBlock', (), {'default': 'doc-full', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 220}), 5: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'max_length': 500, 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'Document', 'max_length': 60, 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('title', 4), ('description', 2), ('document', 5), ('external_url', 6), ('resource_type', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('anchor', 0), ('title', 1), ('description', 2), ('icon', 3), ('resources', 9)]], {})}, verbose_name='Methods, tools and guidance')),
                ('report_groups', wagtail.fields.StreamField([('group', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Short URL-safe name, for example data-rescue.', 'max_length': 60}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 180}), 2: ('wagtail.blocks.TextBlock', (), {'required': False}), 3: ('wagtailiconchooser.blocks.IconChooserBlock', (), {'default': 'doc-full', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 220}), 5: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'max_length': 500, 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'Document', 'max_length': 60, 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('title', 4), ('description', 2), ('document', 5), ('external_url', 6), ('resource_type', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('anchor', 0), ('title', 1), ('description', 2), ('icon', 3), ('resources', 9)]], {})}, verbose_name='Workshop, training and survey reports')),
                ('training_videos', wagtail.fields.StreamField([('video', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 180}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'The value after v= in the YouTube URL.', 'max_length': 24}), 3: ('wagtail.blocks.URLBlock', (), {'max_length': 500}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('youtube_id', 2), ('video_url', 3)]], {})}, verbose_name='Forecast training videos')),
                ('closing_text', wagtail.fields.RichTextField(blank=True, verbose_name='Closing note')),
                ('banner_image', models.ForeignKey(blank=True, help_text='A high quality banner image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Banner Image')),
                ('call_to_action_related_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Call to action related page')),
                ('introduction_button_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Introduction button link')),
                ('introduction_image', models.ForeignKey(blank=True, help_text='A high quality image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Introduction Image')),
                ('search_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Search image')),
            ],
            options={
                'verbose_name': 'RCC Training Page',
            },
            bases=(wagtailmetadata.models.WagtailImageMetadataMixin, 'wagtailcore.page', models.Model, wagtailcache.cache.WagtailCacheMixin),
        ),
    ]
