# Generated by Django 5.2.14 on 2026-09-24 10:02

import django.db.models.deletion
import wagtail.fields
import wagtailcache.cache
import wagtailmetadata.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0043_rcctrainingpage'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RCCRecommendedFunctionsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('banner_title', models.CharField(max_length=255, verbose_name='Banner Title')),
                ('banner_subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Banner Subtitle')),
                ('call_to_action_button_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Call to action button text')),
                ('introduction_title', models.CharField(help_text='Introduction section title', max_length=100, verbose_name='Introduction Title')),
                ('introduction_text', wagtail.fields.RichTextField(help_text='Introduction section description', verbose_name='Introduction text')),
                ('introduction_button_text', models.CharField(blank=True, max_length=20, null=True, verbose_name='Introduction button text')),
                ('introduction_button_link_external', models.URLField(blank=True, help_text='External Link if applicable. Ignored if internal page above is chosen', null=True)),
                ('functions', wagtail.fields.StreamField([('function', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 180}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Product or output', 'max_length': 180}), 2: ('wagtail.blocks.TextBlock', (), {}), 3: ('wagtailiconchooser.blocks.IconChooserBlock', (), {'default': 'globe', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 5: ('wagtail.blocks.ListBlock', (4,), {'label': 'Topics', 'required': False}), 6: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 7: ('wagtail.blocks.URLBlock', (), {'max_length': 500, 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('activity', 0), ('output_title', 1), ('description', 2), ('icon', 3), ('topics', 5), ('related_page', 6), ('external_url', 7), ('link_label', 8)]], {})}, verbose_name='Highly recommended functions')),
                ('evidence_heading', models.CharField(blank=True, default='Research reports and climate-change evidence', max_length=180)),
                ('evidence_introduction', wagtail.fields.RichTextField(blank=True)),
                ('climate_indices_url', models.URLField(blank=True, max_length=500, verbose_name='Climate-change indices application URL')),
                ('closing_text', wagtail.fields.RichTextField(blank=True)),
                ('banner_image', models.ForeignKey(blank=True, help_text='A high quality banner image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Banner Image')),
                ('call_to_action_related_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Call to action related page')),
                ('introduction_button_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Introduction button link')),
                ('introduction_image', models.ForeignKey(blank=True, help_text='A high quality image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Introduction Image')),
                ('search_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Search image')),
            ],
            options={
                'verbose_name': 'RCC Highly Recommended Functions Page',
            },
            bases=(wagtailmetadata.models.WagtailImageMetadataMixin, 'wagtailcore.page', models.Model, wagtailcache.cache.WagtailCacheMixin),
        ),
    ]
