# Generated by Django 5.2.14 on 2026-09-24 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0044_rccrecommendedfunctionspage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rccrecommendedfunctionspage',
            name='climate_indices_url',
        ),
        migrations.RemoveField(
            model_name='rccrecommendedfunctionspage',
            name='closing_text',
        ),
    ]
