# Generated by Django 5.2.14 on 2026-10-08 14:18

import climweb.pages.services.models
import django.core.validators
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0047_service_content_visibility_and_navigation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Training Topic',
                'verbose_name_plural': 'Training Topics',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='onthejobtrainingpage',
            name='proposal_section_introduction',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Proposal form introduction'),
        ),
        migrations.AddField(
            model_name='onthejobtrainingpage',
            name='proposal_section_title',
            field=models.CharField(default='Submit a training proposal', max_length=160, verbose_name='Proposal form title'),
        ),
        migrations.AddField(
            model_name='onthejobtrainingpage',
            name='show_training_proposal_form',
            field=models.BooleanField(default=True, verbose_name='Show online training proposal form'),
        ),
        migrations.CreateModel(
            name='TrainingProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
                ('phone', models.CharField(max_length=80, validators=[django.core.validators.RegexValidator(message='Enter a valid telephone or WhatsApp number.', regex='^\\+?[0-9 ()-]{7,25}$')], verbose_name='Telephone / WhatsApp')),
                ('country', models.CharField(max_length=120, verbose_name='Country')),
                ('job_title', models.CharField(max_length=180, verbose_name='Job title')),
                ('programme_type', models.CharField(choices=[('ojt', 'On-the-job training'), ('secondment', 'Secondment')], default='ojt', max_length=20, verbose_name='Programme type')),
                ('professional_background', models.TextField(verbose_name='Professional background and current responsibilities')),
                ('objectives', models.TextField(verbose_name='Training objectives')),
                ('expected_outcomes', models.TextField(verbose_name='Expected outcomes')),
                ('preferred_start_date', models.DateField(verbose_name='Preferred start date')),
                ('preferred_end_date', models.DateField(verbose_name='Preferred end date')),
                ('nomination_letter', models.FileField(help_text='Required PDF, DOC or DOCX file, maximum 10 MB.', upload_to='training_proposals/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(('pdf', 'doc', 'docx')), climweb.pages.services.models.validate_training_proposal_file_size], verbose_name='Nomination letter')),
                ('cv', models.FileField(help_text='Required PDF, DOC or DOCX file, maximum 10 MB.', upload_to='training_proposals/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(('pdf', 'doc', 'docx')), climweb.pages.services.models.validate_training_proposal_file_size], verbose_name='Curriculum vitae')),
                ('supporting_document', models.FileField(help_text='Required PDF, DOC or DOCX file, maximum 10 MB.', upload_to='training_proposals/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(('pdf', 'doc', 'docx')), climweb.pages.services.models.validate_training_proposal_file_size], verbose_name='Motivation letter or supporting document')),
                ('consent', models.BooleanField(verbose_name='I confirm that the information is accurate and consent to ACMAD using it to assess this training proposal.')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Under review'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='new', max_length=20, verbose_name='Review status')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Internal notes')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted at')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_proposals', to='services.meteorologicalservice', verbose_name='Organisation / NMHS')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_proposals', to='services.onthejobtrainingpage', verbose_name='Training page')),
                ('proposal_title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_proposals', to='services.trainingtopic', verbose_name='Proposed training title')),
            ],
            options={
                'verbose_name': 'Training Proposal',
                'verbose_name_plural': 'Training Proposals',
                'ordering': ('-submitted_at',),
            },
        ),
    ]
