version: '3'

services:
  cms_db:
    container_name: cms_db
    image: postgis/postgis:15-master
    restart: ${RESTART_POLICY}
    environment:
      - POSTGRES_USER=${POSTGRES_USER_CMS}
      - POSTGRES_DB=${POSTGRES_DB_CMS}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_CMS}
    ports:
      - 5432
    volumes:
      - ${CMS_DB_VOLUME}:/var/lib/postgresql/data/
  cms_memcached:
    image: memcached:1.6.12-alpine
    container_name: cms_memcached
    restart: ${RESTART_POLICY}
    ports:
      - "11211"
    entrypoint:
      - memcached
      - -m 1024
      - -I 10m
  cms_web:
    container_name: cms_web
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./docker/cms/Dockerfile
    restart: ${RESTART_POLICY}
    command: sh -c "/wait && gunicorn nmhs_cms.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - 8000
    environment:
      - WAIT_HOSTS=cms_db:5432,cms_memcached:11211
      - WAIT_TIMEOUT=120
      - DEBUG=${DJANGO_DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgis://${POSTGRES_USER_CMS}:${POSTGRES_PASSWORD_CMS}@cms_db:5432/${POSTGRES_DB_CMS}
      - MEMCACHED_URI=cms_memcached:11211
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    ports:
      - 8000
    volumes:
      - ${DJANGO_STATIC_VOLUME}:/home/app/web/static
      - ${DJANGO_MEDIA_VOLUME}:/home/app/web/static
  cms_nginx:
    container_name: cms_nginx
    image: nginx:1.20.2-alpine
    volumes:
      - ${DJANGO_STATIC_VOLUME}:/wagtail_static
      - ${DJANGO_MEDIA_VOLUME}:/wagtail_media
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - cms_web