# Generated by Django 5.2.14 on 2026-10-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediacenter', '0006_alter_mediaindexpage_introduction_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaindexpage',
            name='introduction_video_url',
            field=models.URLField(blank=True, help_text='Optional YouTube or Vimeo URL. When provided, the video replaces the introduction image.', verbose_name='Introduction video URL'),
        ),
    ]
