# Generated by Django 5.2.14 on 2026-10-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediacenter', '0008_alter_mediaindexpage_feature_block_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaindexpage',
            name='more_media_title',
            field=models.CharField(default='More Media', max_length=120, verbose_name='More media section title'),
        ),
    ]
