"""Audited resources published by the legacy ACMAD RCC Training service."""


RCC_TRAINING_DOCUMENTS = (
    {
        "group": "Climate data procedures and indices",
        "title": "Producing CPT input from Climsoft",
        "filename": "procedure-for-cpt-output-from-climsoft.pdf",
        "source_url": "https://rcc.acmad.org/procedure/Procedure_for_CPT_Output_from_CLIMSOFT.pdf",
        "description": "Procedure for preparing Climsoft data for the Climate Predictability Tool.",
    },
    {
        "group": "Climate data procedures and indices",
        "title": "Updating Climsoft from NOAA GTS data",
        "filename": "updating-climsoft-from-noaa-gts-data.pdf",
        "source_url": "https://rcc.acmad.org/procedure/Procedure_for_Updating_CLIMSOFT_Database_from_GTS_Data_Downloaded_from_NOAA_FTP_Site.pdf",
        "description": "Operational procedure for loading GTS observations downloaded from NOAA into Climsoft.",
    },
    {
        "group": "Climate data procedures and indices",
        "title": "RClimDex User Manual",
        "filename": "rclimdex-user-manual.pdf",
        "source_url": "https://rcc.acmad.org/procedure/RClimDexUserManual.pdf",
        "description": "Guidance for quality control, calculation and interpretation of climate-extreme indices.",
    },
    {
        "group": "Data rescue",
        "title": "IEDRO Data Rescue Manual",
        "filename": "iedro-data-rescue-manual.pdf",
        "source_url": "https://rcc.acmad.org/document/IEDRO_manual.pdf",
        "description": "Reference manual for preserving and digitising historical meteorological observations.",
    },
    {
        "group": "Data rescue",
        "title": "Climate Data Rescue Guidance",
        "filename": "climate-data-rescue-guidance.pdf",
        "source_url": "https://rcc.acmad.org/document/Data_Rescue_Eng.pdf",
        "description": "English-language guidance on climate-data rescue activities and workflows.",
    },
    {
        "group": "Climsoft data management",
        "title": "Database Fundamentals",
        "filename": "database-fundamentals.pdf",
        "source_url": "https://rcc.acmad.org/manuelclimsoft/Database%20Fundamentals.pdf",
        "description": "Database concepts and data-management foundations used in Climsoft training.",
    },
    {
        "group": "Climsoft data management",
        "title": "Climsoft installation and reinstallation procedure",
        "filename": "climsoft-installation-and-reinstallation.pptx",
        "source_url": "https://rcc.acmad.org/manuelclimsoft/procedure_installation_et_reintallation_climsoft.pptx",
        "description": "French-language presentation on installing and reinstalling Climsoft.",
    },
    {
        "group": "Climsoft data management",
        "title": "Climsoft Administrator Guide",
        "filename": "climsoft-administrator-guide.pdf",
        "source_url": "https://rcc.acmad.org/manuelclimsoft/Administrator%20Guide.pdf",
        "description": "Administration, configuration, security, maintenance and backup guidance.",
    },
    {
        "group": "Climsoft data management",
        "title": "Climsoft Programmer Guide",
        "filename": "climsoft-programmer-guide.pdf",
        "source_url": "https://rcc.acmad.org/manuelclimsoft/Programmer%20Guide.pdf",
        "description": "Technical guidance for extending and maintaining Climsoft.",
    },
    {
        "group": "Climsoft data management",
        "title": "Climsoft User Guide",
        "filename": "climsoft-user-guide.pdf",
        "source_url": "https://rcc.acmad.org/manuelclimsoft/User%20Guide.pdf",
        "description": "Operational guidance for routine climate-data management in Climsoft.",
    },
    {
        "group": "Climsoft data management",
        "title": "Climsoft Key Entry Guide",
        "filename": "climsoft-key-entry-guide.pdf",
        "source_url": "https://rcc.acmad.org/manuelclimsoft/Key%20Entry%20Guide.pdf",
        "description": "Instructions for climate-observation data entry and capture workflows.",
    },
    {
        "group": "Climate Outlook Forum reports",
        "title": "PRESAO 2013 workshop report",
        "filename": "presao-2013-workshop-report.pdf",
        "source_url": "https://rcc.acmad.org/report/ACMAD_report_workshop_presao_2013.pdf",
        "description": "ACMAD report from the 2013 West Africa Climate Outlook Forum workshop.",
    },
    {
        "group": "Climate Outlook Forum reports",
        "title": "PRESAC 2013 workshop report",
        "filename": "presac-2013-workshop-report.pdf",
        "source_url": "https://rcc.acmad.org/report/ACMAD_report_workshop_presac_2013.pdf",
        "description": "ACMAD report from the 2013 Central Africa Climate Outlook Forum workshop.",
    },
    {
        "group": "Climate Outlook Forum reports",
        "title": "PRESAOI 2013 workshop report",
        "filename": "presaoi-2013-workshop-report.pdf",
        "source_url": "https://rcc.acmad.org/report/ACMAD_report_workshop_presaoi_2013.pdf",
        "description": "ACMAD report from the 2013 Indian Ocean regional outlook workshop.",
    },
    {
        "group": "Climate Outlook Forum reports",
        "title": "PRESANORD 2013 forum report",
        "filename": "presanord-2013-forum-report.pdf",
        "source_url": "https://rcc.acmad.org/report/ACMAD_report_Forum_Presanord_2013.pdf",
        "description": "ACMAD report from the 2013 North Africa Climate Outlook Forum.",
    },
    {
        "group": "Climate Outlook Forum reports",
        "title": "PRESAO 2014 report",
        "filename": "presao-2014-report.pdf",
        "source_url": "https://rcc.acmad.org/report/ACMAD_report_presao_2014.pdf",
        "description": "ACMAD report from the 2014 West Africa Climate Outlook Forum.",
    },
    {
        "group": "Climate Outlook Forum reports",
        "title": "PRESAO 2012 workshop report",
        "filename": "presao-2012-workshop-report.pdf",
        "source_url": "https://rcc.acmad.org/report/ACMAD_report_wokshop_presao_2012.pdf",
        "description": "ACMAD report from the 2012 West Africa Climate Outlook Forum workshop.",
    },
    {
        "group": "Climate Outlook Forum reports",
        "title": "PRESAC 2012 workshop report",
        "filename": "presac-2012-workshop-report.pdf",
        "source_url": "https://rcc.acmad.org/report/ACMAD_report_workshop_presac_2012.pdf",
        "description": "ACMAD report from the 2012 Central Africa Climate Outlook Forum workshop.",
    },
    {
        "group": "Climate Outlook Forum reports",
        "title": "PRESANORD workshop report",
        "filename": "presanord-workshop-report.pdf",
        "source_url": "https://rcc.acmad.org/report/ACMAD_report_wokshop_presanord_2013.pdf",
        "description": "ACMAD report from the North Africa Climate Outlook Forum workshop.",
    },
    {
        "group": "Trainee and scientific-stay reports",
        "title": "Doukpolo training report",
        "filename": "doukpolo-training-report.pdf",
        "source_url": "https://rcc.acmad.org/document/Doukpolo_rapport_final.pdf",
        "description": "Final report from a professional training placement at ACMAD.",
    },
    {
        "group": "Trainee and scientific-stay reports",
        "title": "Isaias Gabriel António Raiva training report",
        "filename": "isaias-raiva-training-report.pdf",
        "source_url": "https://rcc.acmad.org/document/Rapport_Isaias_Gabriel_Ant%C3%B3nio_Raiva.pdf",
        "description": "Report documenting an ACMAD training and knowledge-transfer placement.",
    },
    {
        "group": "Trainee and scientific-stay reports",
        "title": "Justin Mumba action-training report",
        "filename": "justin-mumba-action-training-report.pdf",
        "source_url": "https://rcc.acmad.org/document/Rapport_formation_action_MR_MUMBA_Justin.pdf",
        "description": "Report from an action-training placement completed at ACMAD.",
    },
    {
        "group": "Trainee and scientific-stay reports",
        "title": "Diallo scientific-stay report",
        "filename": "diallo-scientific-stay-report.pdf",
        "source_url": "https://rcc.acmad.org/report/Rapport_diallo_ACMAD.pdf",
        "description": "Scientific-stay report on model output, climate projections and their application in Guinea.",
    },
    {
        "group": "Surveys and analysis",
        "title": "Questionnaire for Global Producing Centres",
        "filename": "questionnaire-for-global-producing-centres.pdf",
        "source_url": "https://rcc.acmad.org/report/Questionnaire_for_GPCs.pdf",
        "description": "Legacy catalogue record for a questionnaire supporting analysis of GPC inputs and regional climate-service requirements. The original download is no longer available.",
        "source_available": False,
    },
)


RCC_TRAINING_DOCUMENTS_BY_TITLE = {
    resource["title"]: resource for resource in RCC_TRAINING_DOCUMENTS
}
