"""Shared metadata for ACMAD's external product importers."""


PRODUCT_IMPORTS = (
    {
        "key": "multihazard",
        "label": "Continental Multi-Hazard Outlook",
        "product_names": ("Continental Multi-Hazard & Advisory Bulletin",),
        "source_label": "ACMAD SGBD/THREDDS",
        "enabled_setting": "ACMAD_MULTIHAZARD_AUTO_IMPORT",
        "interval_setting": "ACMAD_MULTIHAZARD_IMPORT_INTERVAL_HOURS",
        "periodic_task_name": "import-acmad-multihazard-automatically",
        "celery_task": "climweb.pages.products.tasks.run_acmad_multihazard_import",
        "command": "import_acmad_multihazard",
        "limit_setting": "ACMAD_MULTIHAZARD_IMPORT_LIMIT",
        "include_history": True,
        "supports_retry": True,
    },
    {
        "key": "rainfall",
        "label": "Daily Rainfall Monitoring",
        "product_names": ("Daily Rainfall Monitoring",),
        "source_label": "ACMAD SGBD/THREDDS GSMaP",
        "enabled_setting": "ACMAD_RAINFALL_AUTO_IMPORT",
        "interval_setting": "ACMAD_RAINFALL_IMPORT_INTERVAL_HOURS",
        "periodic_task_name": "import-acmad-daily-rainfall-automatically",
        "celery_task": "climweb.pages.products.tasks.run_acmad_daily_rainfall_import",
        "command": "import_acmad_daily_rainfall",
        "limit_setting": "ACMAD_RAINFALL_IMPORT_LIMIT",
        "include_history": True,
        "supports_retry": True,
        "configurable_source": True,
        "source_defaults": {
            "source_type": "html_archive",
            "source_url": (
                "https://sgbd.acmad.org/thredds/fileServer/ACMAD/WWFD/"
                "verificationservice/OBS/ARCHIVE/GSMAP/archive_gsmap.html"
            ),
            "source_system": "ACMAD SGBD/THREDDS GSMaP",
            "allowed_extensions": [".png"],
            "filename_pattern": r"gsmap24_(?P<date>20\d{6})\.png$",
            "date_format": "%Y%m%d",
            "history_url_pattern": r"archive_gsmap_20\d{2}\.html$",
            "request_headers": {},
        },
    },
    {
        "key": "dekadal",
        "label": "Dekadal Climate Bulletin",
        "product_names": ("Dekadal Bulletin",),
        "source_label": "ACMAD RCC / SGBD THREDDS",
        "enabled_setting": "ACMAD_DEKADAL_AUTO_IMPORT",
        "interval_setting": "ACMAD_DEKADAL_IMPORT_INTERVAL_HOURS",
        "periodic_task_name": "import-acmad-dekadal-bulletin-automatically",
        "celery_task": "climweb.pages.products.tasks.run_acmad_dekadal_import",
        "command": "import_acmad_dekadal_bulletin",
        "include_history": True,
        "history_only": True,
    },
    {
        "key": "policy-briefs",
        "label": "Policy and Decision Briefs",
        "product_names": ("Continental Climate Policy", "Policy and Decision Briefs"),
        "source_label": "ACMAD SGBD/THREDDS Policy Briefs",
        "enabled_setting": "ACMAD_POLICY_BRIEFS_AUTO_IMPORT",
        "interval_setting": "ACMAD_POLICY_BRIEFS_IMPORT_INTERVAL_HOURS",
        "periodic_task_name": "import-acmad-policy-briefs-automatically",
        "celery_task": "climweb.pages.products.tasks.run_acmad_policy_briefs_import",
        "command": "import_acmad_policy_briefs",
        "limit_setting": "ACMAD_POLICY_BRIEFS_IMPORT_LIMIT",
    },
    {
        "key": "atmospheric-analysis",
        "label": "Atmospheric Analysis",
        "product_names": ("Atmospheric Analysis",),
        "source_label": "ACMAD Atmospheric Analysis THREDDS",
        "enabled_setting": "ACMAD_ATMOSPHERIC_ANALYSIS_AUTO_IMPORT",
        "interval_setting": "ACMAD_ATMOSPHERIC_ANALYSIS_IMPORT_INTERVAL_HOURS",
        "periodic_task_name": "import-acmad-atmospheric-analysis-automatically",
        "celery_task": "climweb.pages.products.tasks.run_acmad_atmospheric_analysis_import",
        "command": "import_acmad_atmospheric_analysis",
        "include_history": True,
        "history_only": True,
    },
    {
        "key": "heat-stress",
        "label": "Heat and Thermal Stress",
        "product_names": ("Heat and Thermal Stress",),
        "source_label": "ACMAD Heatwave THREDDS",
        "enabled_setting": "ACMAD_HEAT_STRESS_AUTO_IMPORT",
        "interval_setting": "ACMAD_HEAT_STRESS_IMPORT_INTERVAL_HOURS",
        "periodic_task_name": "import-acmad-heat-stress-automatically",
        "celery_task": "climweb.pages.products.tasks.run_acmad_heat_stress_import",
        "command": "import_acmad_heat_stress",
        "limit_setting": "ACMAD_HEAT_STRESS_IMPORT_LIMIT",
        "include_history": True,
        "history_only": True,
    },
    {
        "key": "itd-itcz",
        "label": "ITD and ITCZ Monitoring",
        "product_names": ("ITD and ITCZ Monitoring",),
        "source_label": "ACMAD SGBD THREDDS / CSAG archive",
        "enabled_setting": "ACMAD_ITD_ITCZ_AUTO_IMPORT",
        "interval_setting": "ACMAD_ITD_ITCZ_IMPORT_INTERVAL_HOURS",
        "periodic_task_name": "import-acmad-itd-itcz-automatically",
        "celery_task": "climweb.pages.products.tasks.run_acmad_itd_itcz_import",
        "command": "import_acmad_itd_itcz",
        "limit_setting": "ACMAD_ITD_ITCZ_IMPORT_LIMIT",
        "include_history": True,
        "history_only": True,
    },
    {
        "key": "thunderstorm-nowcasting",
        "label": "Thunderstorm and Nowcasting",
        "product_names": ("Thunderstorm and Nowcasting",),
        "source_label": "ACMAD Satellite THREDDS",
        "enabled_setting": "ACMAD_NOWCASTING_AUTO_IMPORT",
        "interval_setting": "ACMAD_NOWCASTING_IMPORT_INTERVAL_HOURS",
        "periodic_task_name": "import-acmad-thunderstorm-nowcasting-automatically",
        "celery_task": "climweb.pages.products.tasks.run_acmad_nowcasting_import",
        "command": "import_acmad_thunderstorm_nowcasting",
        "limit_setting": "ACMAD_NOWCASTING_IMPORT_LIMIT",
        "include_history": True,
        "history_only": True,
    },
    {
        "key": "climate-health",
        "label": "Climate and Health",
        "product_names": ("Climate and Health",),
        "source_label": "ACMAD WordPress Media",
        "enabled_setting": "ACMAD_CLIMATE_HEALTH_AUTO_IMPORT",
        "interval_setting": "ACMAD_CLIMATE_HEALTH_IMPORT_INTERVAL_HOURS",
        "periodic_task_name": "import-acmad-climate-health-automatically",
        "celery_task": "climweb.pages.products.tasks.run_acmad_climate_health_import",
        "command": "import_acmad_climate_health",
        "limit_setting": "ACMAD_CLIMATE_HEALTH_IMPORT_LIMIT",
        "include_history": True,
        "history_only": True,
    },
    {
        "key": "seasonal-forecasts",
        "label": "Seasonal and Long-Range Forecasts",
        "product_names": (
            "Seasonal Forecast Maps",
            "Seasonal Outlook Bulletins",
            "Consensus Statements and Communiqués",
            "Recommendations and Summaries",
            "Technical Notes",
        ),
        "source_label": "ACMAD WordPress Media + THREDDS",
        "enabled_setting": "ACMAD_SEASONAL_FORECAST_AUTO_IMPORT",
        "interval_setting": "ACMAD_SEASONAL_FORECAST_IMPORT_INTERVAL_HOURS",
        "periodic_task_name": "import-acmad-seasonal-forecasts-automatically",
        "celery_task": "climweb.pages.products.tasks.run_acmad_seasonal_forecast_import",
        "command": "import_acmad_seasonal_forecasts",
        "limit_setting": "ACMAD_SEASONAL_FORECAST_IMPORT_LIMIT",
        "include_history": True,
        "history_only": True,
    },
)


PRODUCT_IMPORTS_BY_KEY = {
    definition["key"]: definition for definition in PRODUCT_IMPORTS
}
