# Generated by Django 5.2.14 on 2026-10-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_newspage_is_el_nino_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='is_el_nino_related',
            field=models.BooleanField(default=False, help_text='Show this news item in the ENSO related activities section.', verbose_name='ENSO related activity'),
        ),
    ]
