# Generated by Django 5.2.14 on 2026-10-02 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_newspage_enso_external_url_and_more'),
        ('products', '0063_ensopartneractivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspage',
            name='enso_external_url',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='enso_host_organisation',
        ),
    ]
