# Generated by Django 5.2.14 on 2026-10-08 11:18

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_alter_vacanciespage_introduction_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancydetailpage',
            name='additional_documents',
            field=wagtail.fields.StreamField([('document', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Document title', 'max_length': 255}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Document'}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('document', 1)]], {})}, verbose_name='Additional job description documents'),
        ),
    ]
