# Generated by Django 5.2.14 on 2026-07-18 20:23

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contactpage_enable_submission_ratings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='notification_emails',
            field=wagtail.fields.StreamField([('email', 0)], blank=True, block_lookup={0: ('wagtail.blocks.EmailBlock', (), {'label': 'Email address'})}, help_text='Receives a weekly submission-count digest, and (if a closing date is configured) a summary the day before it closes.', verbose_name='Notification emails'),
        ),
    ]
