# Generated by Django 5.2.14 on 2026-07-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_contactpage_notification_emails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactformfield',
            options={},
        ),
        migrations.AddField(
            model_name='contactformfield',
            name='max_length',
            field=models.PositiveIntegerField(blank=True, help_text='Only applies to the "Multi-line text" field type - leave blank for no limit.', null=True, verbose_name='Maximum characters'),
        ),
    ]
