# Generated by Django 5.2.14 on 2026-07-20 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_request', '0006_alter_datarequestformfield_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datarequestformfield',
            options={'ordering': ['sort_order']},
        ),
    ]
