# Generated by Django 5.2.14 on 2026-08-13 07:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_submissionemaillog'),
        ('products', '0046_productimportrun_cancellation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguredProductImporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Stable identifier used by import runs and schedules.', max_length=80, unique=True, verbose_name='Importer Key')),
                ('label', models.CharField(max_length=255, verbose_name='Importer Name')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active')], default='draft', max_length=20)),
                ('default_interval_hours', models.PositiveIntegerField(default=24, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(720)], verbose_name='Default Interval Hours')),
                ('default_source_config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configured_product_importers', to=settings.AUTH_USER_MODEL)),
                ('product_item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configured_importers', to='base.productitemtype', verbose_name='Destination Product Type')),
                ('product_page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configured_importers', to='products.productpage', verbose_name='Destination Product Page')),
            ],
            options={
                'verbose_name': 'Configured Product Importer',
                'verbose_name_plural': 'Configured Product Importers',
                'ordering': ['label'],
            },
        ),
    ]
