# Generated by Django 5.2.14 on 2026-08-13 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0047_configuredproductimporter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuredproductimporter',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='ConfiguredProductImporterAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('archived', 'Archived'), ('restored', 'Restored'), ('enabled', 'Enabled'), ('disabled', 'Disabled'), ('source_updated', 'Source updated'), ('schedule_updated', 'Schedule updated')], max_length=40)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configured_importer_audit_events', to=settings.AUTH_USER_MODEL)),
                ('importer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='products.configuredproductimporter')),
            ],
            options={
                'verbose_name': 'Configured Product Importer Audit Event',
                'verbose_name_plural': 'Configured Product Importer Audit Events',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
