# Generated by Django 5.2.14 on 2026-08-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0048_alter_configuredproductimporter_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productpage",
            name="homepage_feature_order",
            field=models.PositiveIntegerField(
                blank=True,
                help_text=(
                    "Controls the order of products selected for the homepage. "
                    "Lower numbers appear first."
                ),
                null=True,
                verbose_name="Homepage feature order",
            ),
        ),
    ]
