# Generated by Django 5.2.14 on 2026-08-17 08:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0049_productpage_homepage_feature_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending confirmation'), ('active', 'Active'), ('unsubscribed', 'Unsubscribed'), ('bounced', 'Bounced')], default='pending', max_length=20)),
                ('confirmation_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('unsubscribe_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('consented_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('consent_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('consent_user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product subscriber',
                'verbose_name_plural': 'Product subscribers',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='ProductNotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_family', models.SlugField(max_length=80)),
                ('trigger', models.CharField(choices=[('automatic', 'Automatic import'), ('manual', 'Dashboard action')], max_length=20)),
                ('automatic_key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_notification_events', to=settings.AUTH_USER_MODEL)),
                ('source_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_events', to='products.productsourceimport')),
            ],
            options={
                'verbose_name': 'Product notification event',
                'verbose_name_plural': 'Product notification events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductNotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='products.productnotificationevent')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='products.productsubscriber')),
            ],
            options={
                'ordering': ['subscriber__email'],
                'constraints': [models.UniqueConstraint(fields=('event', 'subscriber'), name='unique_product_notification_delivery')],
            },
        ),
        migrations.CreateModel(
            name='ProductSubscriptionPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_family', models.SlugField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='products.productsubscriber')),
            ],
            options={
                'ordering': ['product_family'],
                'constraints': [models.UniqueConstraint(fields=('subscriber', 'product_family'), name='unique_product_subscription_preference')],
            },
        ),
    ]
