# Generated by Django 5.2.14 on 2026-08-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0050_productsubscriber_productnotificationevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsubscriber',
            name='organization_type',
            field=models.CharField(blank=True, choices=[('Public Sector', 'Public Sector'), ('Intergovernmental Organisation', 'Intergovernmental Organisation'), ('Private Sector', 'Private Sector'), ('Academic/Research', 'Academic/Research'), ('Media', 'Media'), ('Youth', 'Youth'), ('Donor/Finance institutions', 'Donor/Finance institutions'), ('Non Governmental Organisation (NGO)', 'Non Governmental Organisation (NGO)'), ('Others', 'Others')], max_length=100),
        ),
        migrations.AddField(
            model_name='productsubscriber',
            name='sector',
            field=models.CharField(blank=True, choices=[('Agriculture', 'Agriculture'), ('Aviation', 'Aviation'), ('Marine', 'Marine'), ('Media', 'Media'), ('Environment', 'Environment'), ('Tourism', 'Tourism'), ('Security', 'Security'), ('Civil Protection', 'Civil Protection'), ('Telecommunication', 'Telecommunication'), ('Health', 'Health'), ('Banking and Finance', 'Banking and Finance'), ('Research', 'Research'), ('Water and Sanitation', 'Water and Sanitation'), ('Others', 'Others')], max_length=80),
        ),
    ]
