# Generated by Django 5.2.14 on 2026-08-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0051_productsubscriber_organization_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFamilyNotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_family', models.SlugField(max_length=80, unique=True, verbose_name='Product Family')),
                ('notifications_enabled', models.BooleanField(default=True, help_text='If disabled, no notifications will be sent for this product family.', verbose_name='Notifications Enabled')),
                ('custom_subject', models.CharField(blank=True, help_text='Optional. Use {{ product_label }} and {{ date }} as variables.', max_length=255, verbose_name='Custom Email Subject')),
                ('introduction_text', models.TextField(blank=True, help_text='Optional text to appear at the top of the notification email.', verbose_name='Email Introduction Text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product family notification config',
                'verbose_name_plural': 'Product family notification configs',
            },
        ),
        migrations.AlterField(
            model_name='productsubscriber',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('unsubscribed', 'Unsubscribed'), ('bounced', 'Bounced')], default='pending', max_length=20),
        ),
    ]
