# Generated by Django 5.2.14 on 2026-08-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0052_productfamilynotificationconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsubscriber',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
