# Generated by Django 5.2.14 on 2026-08-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0054_productsubscriber_extra_data_productsubscriptionpage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsubscriptionpage',
            name='form_open',
            field=models.BooleanField(default=True, help_text='Turn off to immediately stop accepting submissions, regardless of any closing date configured below.', verbose_name='Form open'),
        ),
    ]
