# Generated by Django 5.2.14 on 2026-10-02 07:32

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


OLD_INTRODUCTION = (
    "<p>El Niño is a warming of the central and eastern tropical Pacific Ocean that can influence "
    "weather patterns around the world. Across Africa, its effects are not uniform: the timing, "
    "strength and location of rainfall and temperature changes differ between regions and seasons.</p>"
    "<p>ACMAD provides a continental view that complements national and regional information, helping "
    "decision-makers understand where conditions may create heightened risks or opportunities.</p>"
)
NEW_INTRODUCTION = (
    "<p>The El Niño–Southern Oscillation (ENSO) is a recurring variation in tropical Pacific Ocean "
    "temperatures and atmospheric circulation. Its El Niño, La Niña and neutral phases can influence "
    "weather patterns around the world.</p>"
    "<p>Across Africa, ENSO effects are not uniform: the timing, strength and location of rainfall and "
    "temperature changes differ between regions and seasons.</p>"
    "<p>ACMAD provides a continental view that complements national and regional information, helping "
    "decision-makers understand where conditions may create heightened risks or opportunities.</p>"
)
OLD_AFRICA_CONTEXT = (
    "<p>El Niño can shift rainfall and temperature patterns across Africa, with impacts that vary "
    "by region and season. These changes can affect water availability, agriculture, food security, "
    "health, energy and disaster risk.</p>"
)
NEW_AFRICA_CONTEXT = (
    "<p>ENSO can shift rainfall and temperature patterns across Africa through its El Niño, La Niña "
    "and neutral phases. The effects vary by region and season and can influence water availability, "
    "agriculture, food security, health, energy and disaster risk.</p>"
)


def update_existing_enso_content(apps, schema_editor):
    ElNinoPage = apps.get_model('products', 'ElNinoPage')
    Product = apps.get_model('base', 'Product')
    ProductItemType = apps.get_model('base', 'ProductItemType')

    for page in ElNinoPage.objects.all():
        changed = []
        if page.title == "El Niño in Africa":
            page.title = "ENSO in Africa"
            changed.append("title")
        if page.draft_title == "El Niño in Africa":
            page.draft_title = "ENSO in Africa"
            changed.append("draft_title")
        if page.introduction_title == "Understanding El Niño and its implications for Africa":
            page.introduction_title = "Understanding ENSO and its implications for Africa"
            changed.append("introduction_title")
        if page.introduction_text == OLD_INTRODUCTION:
            page.introduction_text = NEW_INTRODUCTION
            changed.append("introduction_text")
        if page.africa_context == OLD_AFRICA_CONTEXT:
            page.africa_context = NEW_AFRICA_CONTEXT
            changed.append("africa_context")
        if page.search_description == "ACMAD El Niño monitoring, outlooks, impacts and monthly bulletins for Africa.":
            page.search_description = "ACMAD ENSO monitoring, outlooks, impacts and monthly bulletins for Africa."
            changed.append("search_description")
        if changed:
            page.save(update_fields=changed)

    Product.objects.filter(name="El Niño Bulletin").update(name="ENSO Bulletin")
    ProductItemType.objects.filter(name="El Niño Bulletin").update(name="ENSO Bulletin")


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0058_elninopage_explainer_image'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elninopage',
            options={'verbose_name': 'ENSO Page', 'verbose_name_plural': 'ENSO Pages'},
        ),
        migrations.AlterField(
            model_name='elninopage',
            name='africa_context',
            field=wagtail.fields.RichTextField(default='<p>ENSO can shift rainfall and temperature patterns across Africa through its El Niño, La Niña and neutral phases. The effects vary by region and season and can influence water availability, agriculture, food security, health, energy and disaster risk.</p>', verbose_name='ENSO in Africa'),
        ),
        migrations.AlterField(
            model_name='elninopage',
            name='explainer_image',
            field=models.ForeignKey(blank=True, help_text='Upload the image or infographic that explains ENSO and its phases.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='ENSO explainer image'),
        ),
        migrations.RunPython(update_existing_enso_content, migrations.RunPython.noop),
    ]
