# Generated by Django 5.2.14 on 2026-10-02 16:16

import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
from django.db import migrations, models


def migrate_existing_partner_activities(apps, schema_editor):
    ElNinoPage = apps.get_model('products', 'ElNinoPage')
    ENSOPartnerActivity = apps.get_model('products', 'ENSOPartnerActivity')
    EventPage = apps.get_model('events', 'EventPage')
    NewsPage = apps.get_model('news', 'NewsPage')

    enso_page = ElNinoPage.objects.first()
    if not enso_page:
        return

    for event in EventPage.objects.exclude(enso_host_organisation='').exclude(enso_external_url=''):
        ENSOPartnerActivity.objects.get_or_create(
            page_id=enso_page.pk,
            title=event.title,
            external_url=event.enso_external_url,
            defaults={
                'date': event.date_from.date(),
                'activity_type': 'event',
                'host_organisation': event.enso_host_organisation,
                'image_id': event.image_id,
            },
        )

    for news_item in NewsPage.objects.exclude(enso_host_organisation='').exclude(enso_external_url=''):
        ENSOPartnerActivity.objects.get_or_create(
            page_id=enso_page.pk,
            title=news_item.title,
            external_url=news_item.enso_external_url,
            defaults={
                'date': news_item.date.date(),
                'activity_type': 'news',
                'host_organisation': news_item.enso_host_organisation,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_eventpage_enso_external_url_and_more'),
        ('news', '0009_newspage_enso_external_url_and_more'),
        ('products', '0062_alter_elninopage_acmad_response_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ENSOPartnerActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date')),
                ('activity_type', models.CharField(choices=[('event', 'Event'), ('news', 'News'), ('briefing', 'Briefing'), ('workshop', 'Workshop'), ('other', 'Other')], default='event', max_length=20, verbose_name='Activity type')),
                ('host_organisation', models.CharField(max_length=255, verbose_name='Hosting organisation')),
                ('external_url', models.URLField(max_length=1000, verbose_name='External activity URL')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_activities', to='products.elninopage')),
            ],
            options={
                'verbose_name': 'ENSO partner activity',
                'verbose_name_plural': 'ENSO partner activities',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RunPython(migrate_existing_partner_activities, migrations.RunPython.noop),
    ]
