# Generated by Django 5.2.14 on 2026-10-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0063_ensopartneractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='elninopage',
            name='explainer_image_caption',
            field=models.CharField(blank=True, help_text='Optional caption displayed directly below the ENSO explainer image.', max_length=500, verbose_name='ENSO explainer image caption'),
        ),
    ]
