# Generated by Django 5.2.14 on 2026-10-02 16:54

import wagtail.fields
from django.db import migrations


OLD_AFRICA_CONTEXT_TEXT = (
    "ENSO develops through interactions between the tropical Pacific Ocean and the atmosphere. "
    "During El Niño, surface waters in the central and eastern Pacific become warmer than average and "
    "trade winds often weaken. During La Niña, the same waters become cooler than average and trade winds "
    "strengthen. Between these phases, conditions are described as neutral."
)
NEW_AFRICA_CONTEXT_TEXT = (
    "ENSO links changes in the tropical Pacific Ocean with the atmosphere. El Niño is the warm phase, "
    "La Niña the cool phase, and neutral conditions occur between them."
)
OLD_ACMAD_RESPONSE_TEXT = (
    "These ocean and atmosphere changes can reorganize tropical rainfall and influence circulation far "
    "beyond the Pacific. Across Africa, the signal varies by region and season, so ENSO does not produce "
    "the same outcome everywhere. Its effects are interpreted alongside other climate drivers and local "
    "conditions when assessing possible changes in rainfall, temperature, drought and flood risk."
)
NEW_ACMAD_RESPONSE_TEXT = (
    "These phases can influence rainfall and temperature across Africa, but their effects vary by region "
    "and season and must be considered alongside other climate drivers."
)


def shorten_existing_explanation(apps, schema_editor):
    ElNinoPage = apps.get_model('products', 'ElNinoPage')

    for page in ElNinoPage.objects.all():
        changed = []
        africa_context = str(page.africa_context)
        if OLD_AFRICA_CONTEXT_TEXT in africa_context:
            page.africa_context = africa_context.replace(OLD_AFRICA_CONTEXT_TEXT, NEW_AFRICA_CONTEXT_TEXT)
            changed.append('africa_context')

        acmad_response = str(page.acmad_response)
        if OLD_ACMAD_RESPONSE_TEXT in acmad_response:
            page.acmad_response = acmad_response.replace(OLD_ACMAD_RESPONSE_TEXT, NEW_ACMAD_RESPONSE_TEXT)
            changed.append('acmad_response')

        if changed:
            page.save(update_fields=changed)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0064_elninopage_explainer_image_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elninopage',
            name='acmad_response',
            field=wagtail.fields.RichTextField(default='<p>These phases can influence rainfall and temperature across Africa, but their effects vary by region and season and must be considered alongside other climate drivers.</p>', verbose_name='ENSO explanation — African impacts'),
        ),
        migrations.AlterField(
            model_name='elninopage',
            name='africa_context',
            field=wagtail.fields.RichTextField(default='<p>ENSO links changes in the tropical Pacific Ocean with the atmosphere. El Niño is the warm phase, La Niña the cool phase, and neutral conditions occur between them.</p>', verbose_name='ENSO explanation — phases'),
        ),
        migrations.RunPython(shorten_existing_explanation, migrations.RunPython.noop),
    ]
