# Generated by Django 5.2.14 on 2026-10-06 14:24

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0065_alter_elninopage_acmad_response_and_more'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productindexpage',
            name='introduction_button_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Introduction button link'),
        ),
        migrations.AddField(
            model_name='productindexpage',
            name='introduction_button_link_external',
            field=models.URLField(blank=True, help_text='External Link if applicable. Ignored if internal page above is chosen', null=True),
        ),
        migrations.AddField(
            model_name='productindexpage',
            name='introduction_button_text',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Introduction button text'),
        ),
        migrations.AddField(
            model_name='productindexpage',
            name='introduction_image',
            field=models.ForeignKey(blank=True, help_text='A high quality image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Introduction Image'),
        ),
        migrations.AddField(
            model_name='productindexpage',
            name='introduction_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Introduction section description', null=True, verbose_name='Introduction text'),
        ),
        migrations.AddField(
            model_name='productindexpage',
            name='introduction_title',
            field=models.CharField(blank=True, help_text='Introduction section title', max_length=100, null=True, verbose_name='Introduction Title'),
        ),
    ]
