# Generated by Django 5.2.14 on 2026-10-06 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0066_productindexpage_introduction_button_link_and_more'),
        ('products', '0068_merge_enso_explanation_fields'),
    ]

    operations = [
    ]
