# Generated by Django 5.2.14 on 2026-10-07 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0069_merge_20261006_1815'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='productindexpage',
            name='featured_product',
            field=models.ForeignKey(blank=True, help_text='Product shown beside the introduction on the Products page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Featured product'),
        ),
    ]
