# Generated by Django 5.2.14 on 2026-10-06 14:24

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_projectindexpage_introduction_button_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectindexpage',
            name='introduction_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Introduction section description', null=True, verbose_name='Introduction text'),
        ),
        migrations.AlterField(
            model_name='projectindexpage',
            name='introduction_title',
            field=models.CharField(blank=True, help_text='Introduction section title', max_length=100, null=True, verbose_name='Introduction Title'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='introduction_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Introduction section description', null=True, verbose_name='Introduction text'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='introduction_title',
            field=models.CharField(blank=True, help_text='Introduction section title', max_length=100, null=True, verbose_name='Introduction Title'),
        ),
    ]
