# Generated by Django 5.2.14 on 2026-10-08 13:09

import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_projectindexpage_introduction_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='projectpage',
            name='sectors',
            field=modelcluster.fields.ParentalManyToManyField(help_text='Select at least one sector for this project.', related_name='projects', to='projects.projectsector', verbose_name='Sectors'),
        ),
    ]
