# Generated by Django 5.2.14 on 2026-08-27 09:16

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_homepage_hero_featured_products'),
        ('staff', '0002_alter_staffpage_introduction_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='dg_message',
            field=wagtail.fields.RichTextField(default='Across Africa, climate information becomes most valuable when it reaches people in time to guide action. ACMAD is committed to turning science, regional cooperation and innovation into trusted services that help institutions and communities anticipate risk and build lasting resilience.', verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='dg_message_closing',
            field=models.CharField(blank=True, default='Science in service of people, partnerships and preparedness.', max_length=200, verbose_name='Closing statement'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='dg_message_heading',
            field=models.CharField(default="DG/CEO's message", max_length=120, verbose_name='Section heading'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='dg_message_staff_member',
            field=models.ForeignKey(blank=True, help_text='Select the staff profile whose name, title and photograph should appear with the message.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.staffmember', verbose_name='DG/CEO staff member'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_dg_message',
            field=models.BooleanField(default=True, verbose_name='Show DG/CEO message section'),
        ),
    ]
