# Generated by Django 5.2.14 on 2026-10-02 07:32

import climweb.pages.home.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_homepage_hero_carousel_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='show_enso_section',
            field=models.BooleanField(default=True, help_text='Show the ENSO feature section on the homepage when a live ENSO page is available.', verbose_name='Show ENSO section'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_carousel_order',
            field=wagtail.fields.StreamField([('news', 0), ('event', 1), ('el_nino', 2), ('summer_school', 3)], blank=True, block_lookup={0: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'News slide', 'label': 'News'}), 1: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'Event slide', 'label': 'Event'}), 2: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'ENSO slide', 'label': 'ENSO'}), 3: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'Summer School slide', 'label': 'Summer School'})}, default=climweb.pages.home.models.default_hero_carousel_order, help_text='In Manual mode, drag these items into the order they should appear. Missing or disabled slides are skipped.', verbose_name='Slide order'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_show_el_nino',
            field=models.BooleanField(default=True, help_text='Include the ENSO programme slide in the carousel.', verbose_name='Show ENSO'),
        ),
    ]
