# Generated by Django 5.2.14 on 2026-10-07 10:35

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_homepage_show_enso_section_and_more'),
        ('summer_school', '0014_alter_summerschoolindexpage_editions_per_page'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='homepage_summer_school',
            field=models.ForeignKey(blank=True, help_text='Choose the edition featured on the homepage. Leave empty to use the latest featured edition.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='summer_school.summerschoolpage', verbose_name='Summer School edition'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_summer_school_section',
            field=models.BooleanField(default=True, verbose_name='Show Summer School section'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='summer_school_section_button_text',
            field=models.CharField(blank=True, default='Learn more', max_length=60, verbose_name='Button text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='summer_school_section_description',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Section description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='summer_school_section_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Section image override'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='summer_school_section_label',
            field=models.CharField(blank=True, default='Summer School', max_length=100, verbose_name='Section label'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='summer_school_section_title',
            field=models.CharField(blank=True, help_text="Leave empty to use the selected edition's heading.", max_length=255, verbose_name='Section title override'),
        ),
    ]
