# Generated by Django 5.2.14 on 2026-10-08 11:18

import climweb.pages.home.models
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_remove_eventpage_enso_external_url_and_more'),
        ('home', '0050_homepage_homepage_summer_school_and_more'),
        ('news', '0010_remove_newspage_enso_external_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_featured_event_2',
            field=models.ForeignKey(blank=True, help_text='Optional second event page for the carousel in Manual mode.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.eventpage', verbose_name='Second event slide'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_featured_news_2',
            field=models.ForeignKey(blank=True, help_text='Optional second news page for the carousel in Manual mode.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='news.newspage', verbose_name='Second news slide'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_carousel_order',
            field=wagtail.fields.StreamField([('news', 0), ('news_2', 1), ('event', 2), ('event_2', 3), ('el_nino', 4), ('summer_school', 5)], blank=True, block_lookup={0: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'News slide', 'label': 'News'}), 1: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'Second news slide', 'label': 'Second news'}), 2: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'Event slide', 'label': 'Event'}), 3: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'Second event slide', 'label': 'Second event'}), 4: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'ENSO slide', 'label': 'ENSO'}), 5: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'Summer School slide', 'label': 'Summer School'})}, default=climweb.pages.home.models.default_hero_carousel_order, help_text='In Manual mode, drag these items into the order they should appear. Missing or disabled slides are skipped.', verbose_name='Slide order'),
        ),
    ]
