# Generated by Django 5.2.14 on 2026-10-09 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_homepage_hero_featured_event_2_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionalclimatecentre',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='Optional official centre logo shown on the RCC directory page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='regionalclimatecentre',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Visible on homepage and RCC directory'),
        ),
    ]
