# Generated by Django 5.2.14 on 2026-10-09 09:38

import django.core.validators
import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


def configure_rcc_networks(apps, schema_editor):
    RegionalClimateCentre = apps.get_model('home', 'RegionalClimateCentre')
    MapNode = apps.get_model('home', 'RegionalClimateCentreMapNode')

    north_africa = RegionalClimateCentre.objects.filter(
        display_name__icontains='Network NA'
    ).first()
    if north_africa:
        north_africa.centre_type = 'network'
        north_africa.coverage = 'Northern Africa'
        north_africa.save(update_fields=['centre_type', 'coverage'])
        for order, (name, x, y) in enumerate((
            ('Algiers', '68.0', '7.0'),
            ('Tunis', '82.0', '5.0'),
            ('Tripoli', '96.0', '18.0'),
            ('Cairo', '119.0', '34.0'),
        )):
            MapNode.objects.get_or_create(
                centre=north_africa,
                name=name,
                defaults={'map_x': x, 'map_y': y, 'sort_order': order},
            )

    swio, _ = RegionalClimateCentre.objects.update_or_create(
        display_name='SWIO RCC-Network',
        defaults={
            'full_name': 'South-West Indian Ocean RCC-Network',
            'centre_type': 'network',
            'city': '',
            'country': '',
            'coverage': 'South-West Indian Ocean',
            'website_url': 'https://wmo.int/activities/csis/rcc/regional-climate-centre-africa',
            'status': 'initiated',
            'map_x': '254.0',
            'map_y': '158.0',
            'label_position': 'lower_left',
            'order': 70,
            'is_active': True,
        },
    )
    for order, (x, y) in enumerate((('254.0', '225.0'), ('262.0', '223.0'))):
        MapNode.objects.get_or_create(
            centre=swio,
            map_x=x,
            map_y=y,
            defaults={'map_y': y, 'sort_order': order},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_regionalclimatecentre_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionalclimatecentre',
            name='centre_type',
            field=models.CharField(choices=[('centre', 'Regional Climate Centre'), ('network', 'RCC Network')], default='centre', max_length=20, verbose_name='Entry type'),
        ),
        migrations.AddField(
            model_name='regionalclimatecentre',
            name='coverage',
            field=models.CharField(blank=True, help_text='Especially useful for an RCC Network, for example Northern Africa.', max_length=180, verbose_name='Geographical coverage'),
        ),
        migrations.AlterField(
            model_name='regionalclimatecentre',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='regionalclimatecentre',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='regionalclimatecentre',
            name='status',
            field=models.CharField(choices=[('designated', 'WMO designated'), ('demonstration', 'In demonstration'), ('initiated', 'Initiated')], default='designated', max_length=20, verbose_name='RCC status'),
        ),
        migrations.AlterField(
            model_name='regionalclimatecentre',
            name='map_x',
            field=models.DecimalField(decimal_places=1, help_text='SVG horizontal coordinate from 0 (left) to 280 (right).', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(280)], verbose_name='Horizontal map position'),
        ),
        migrations.CreateModel(
            name='RegionalClimateCentreMapNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Node name')),
                ('map_x', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(280)], verbose_name='Horizontal map position')),
                ('map_y', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(270)], verbose_name='Vertical map position')),
                ('centre', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_map_nodes', to='home.regionalclimatecentre')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RunPython(configure_rcc_networks, migrations.RunPython.noop),
    ]
