# Generated by Django 5.2.14 on 2026-10-09 10:26

import wagtail.fields
from django.db import migrations
import uuid


def migrate_featured_updates(apps, schema_editor):
    HomePage = apps.get_model('home', 'HomePage')
    field_map = {
        'news': ('news', 'hero_featured_news_id'),
        'news_2': ('news', 'hero_featured_news_2_id'),
        'event': ('event', 'hero_featured_event_id'),
        'event_2': ('event', 'hero_featured_event_2_id'),
    }

    for homepage in HomePage.objects.all():
        order = [block.block_type for block in homepage.hero_carousel_order]
        if not order:
            order = ['news', 'news_2', 'event', 'event_2']

        updates = []
        for slot in order:
            if slot not in field_map:
                continue
            block_type, field_name = field_map[slot]
            page_id = getattr(homepage, field_name)
            if page_id:
                updates.append({
                    'type': block_type,
                    'value': page_id,
                    'id': str(uuid.uuid4()),
                })
        homepage.hero_featured_updates = updates[:5]
        homepage.save(update_fields=['hero_featured_updates'])


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_regionalclimatecentre_centre_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_featured_updates',
            field=wagtail.fields.StreamField([('news', 0), ('event', 1)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {'label': 'News', 'page_type': ['news.NewsPage']}), 1: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Event', 'page_type': ['events.EventPage']})}, help_text='Choose up to five news or event pages. Drag the items to set their carousel order.', verbose_name='Featured news and events'),
        ),
        migrations.RunPython(migrate_featured_updates, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_carousel_order',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_featured_event',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_featured_event_2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_featured_news',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_featured_news_2',
        ),
    ]
