# Generated by Django 5.2.14 on 2026-07-18 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_submissionreview'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_ids', models.JSONField(default=list)),
                ('recipients', models.JSONField(default=list, help_text='Email addresses actually sent to')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('attachment_names', models.JSONField(blank=True, default=list)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Submission Email Log',
                'verbose_name_plural': 'Submission Email Logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
