# Generated by Django 5.2.14 on 2026-08-20 10:51

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0045_submissionexportjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="navigationsettings",
            name="header_utility_links",
            field=wagtail.fields.StreamField(
                [("utility_link", 6)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Label", "max_length": 60}),
                    1: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Select a page, or provide an external URL below.",
                            "label": "Internal page",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Used instead of the internal page when provided.",
                            "label": "External URL",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtailiconchooser.blocks.IconChooserBlock",
                        (),
                        {"label": "Icon", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "label": "Open in a new tab", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": True, "label": "Enabled", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 0),
                                ("page", 1),
                                ("external_url", 2),
                                ("icon", 3),
                                ("open_in_new_tab", 4),
                                ("enabled", 5),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="Add, reorder, enable, or disable links shown in the header utility bar.",
                null=True,
                verbose_name="Header utility links",
            ),
        ),
    ]
