# Generated by Django 5.2.14 on 2026-08-20 11:42

import wagtail_color_panel.fields
from django.db import migrations, models


def seed_acmad_portal_theme(apps, schema_editor):
    Theme = apps.get_model("base", "Theme")
    if Theme.objects.filter(name="ACMAD Portal").exists():
        return

    Theme.objects.create(
        name="ACMAD Portal",
        is_default=not Theme.objects.filter(is_default=True).exists(),
        primary_hover_color="#087a5a",
        primary_color="#132a35",
        secondary_color="#f8f7f3",
        header_background_color="#071f2e",
        heading_color="#0b2b3d",
        secondary_dark_color="#123e52",
        primary_hover_state_color="#0b946b",
        primary_light_color="#dff4eb",
        accent_color="#f4c84a",
        accent_hover_color="#f8d66f",
        info_background_color="#e8f2f5",
        surface_color="#ffffff",
        muted_text_color="#61727b",
        border_color="#dce4e5",
        danger_color="#b93535",
        body_font="dm_sans",
        heading_font="manrope",
        shadow_sm="0 8px 28px rgba(9, 42, 55, 0.08)",
        shadow_lg="0 24px 70px rgba(2, 24, 35, 0.20)",
        border_radius=5,
        box_shadow=8,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0046_navigationsettings_header_utility_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="accent_color",
            field=wagtail_color_panel.fields.ColorField(
                blank=True, max_length=7, null=True, verbose_name="Accent color"
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="accent_hover_color",
            field=wagtail_color_panel.fields.ColorField(
                blank=True, max_length=7, null=True, verbose_name="Accent hover color"
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="body_font",
            field=models.CharField(
                choices=[
                    ("open_sans", "Open Sans"),
                    ("dm_sans", "DM Sans"),
                    ("manrope", "Manrope"),
                    ("system", "System font"),
                ],
                default="open_sans",
                max_length=20,
                verbose_name="Body font",
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="border_color",
            field=wagtail_color_panel.fields.ColorField(
                blank=True, max_length=7, null=True, verbose_name="Border color"
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="danger_color",
            field=wagtail_color_panel.fields.ColorField(
                blank=True, max_length=7, null=True, verbose_name="Danger and error color"
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="header_background_color",
            field=wagtail_color_panel.fields.ColorField(
                blank=True, max_length=7, null=True, verbose_name="Header and footer background"
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="heading_color",
            field=wagtail_color_panel.fields.ColorField(
                blank=True, max_length=7, null=True, verbose_name="Heading and navigation color"
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="heading_font",
            field=models.CharField(
                choices=[
                    ("open_sans", "Open Sans"),
                    ("dm_sans", "DM Sans"),
                    ("manrope", "Manrope"),
                    ("system", "System font"),
                ],
                default="open_sans",
                max_length=20,
                verbose_name="Heading font",
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="info_background_color",
            field=wagtail_color_panel.fields.ColorField(
                blank=True, max_length=7, null=True, verbose_name="Information background"
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="muted_text_color",
            field=wagtail_color_panel.fields.ColorField(
                blank=True, max_length=7, null=True, verbose_name="Muted text color"
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="primary_hover_state_color",
            field=wagtail_color_panel.fields.ColorField(
                blank=True, max_length=7, null=True, verbose_name="Primary hover color"
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="primary_light_color",
            field=wagtail_color_panel.fields.ColorField(
                blank=True, max_length=7, null=True, verbose_name="Primary light background"
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="restore_acmad_portal_defaults",
            field=models.BooleanField(
                default=False,
                help_text="Replace this theme's colors, fonts, radius, and shadows with the ACMAD Portal preset.",
                verbose_name="Restore ACMAD Portal defaults on save",
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="secondary_dark_color",
            field=wagtail_color_panel.fields.ColorField(
                blank=True, max_length=7, null=True, verbose_name="Secondary dark color"
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="shadow_lg",
            field=models.CharField(
                blank=True,
                default="",
                help_text="CSS box-shadow used for overlays and featured panels.",
                max_length=120,
                verbose_name="Large shadow",
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="shadow_sm",
            field=models.CharField(
                blank=True,
                default="",
                help_text="CSS box-shadow used for cards and dropdowns.",
                max_length=120,
                verbose_name="Small shadow",
            ),
        ),
        migrations.AddField(
            model_name="theme",
            name="surface_color",
            field=wagtail_color_panel.fields.ColorField(
                blank=True, max_length=7, null=True, verbose_name="Card and navigation surface"
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="primary_color",
            field=wagtail_color_panel.fields.ColorField(
                blank=True,
                default="#363636",
                help_text="Default color for body copy",
                max_length=7,
                null=True,
                verbose_name="Body text color",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="primary_hover_color",
            field=wagtail_color_panel.fields.ColorField(
                blank=True,
                default="#176c9c",
                help_text="Main interactive and button color",
                max_length=7,
                null=True,
                verbose_name="Primary brand color",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="secondary_color",
            field=wagtail_color_panel.fields.ColorField(
                blank=True,
                default="#ffffff",
                help_text="Default page background",
                max_length=7,
                null=True,
                verbose_name="Page background color",
            ),
        ),
        migrations.RunPython(seed_acmad_portal_theme, migrations.RunPython.noop),
    ]
