# Generated by Django 5.2.14 on 2026-08-20

from django.db import migrations, models


CLIMWEB_DEFAULTS = {
    "primary_hover_color": "#176c9c",
    "primary_color": "#363636",
    "secondary_color": "#ffffff",
    "header_background_color": "#176c9c",
    "heading_color": "#363636",
    "secondary_dark_color": "#0c447c",
    "primary_hover_state_color": "#0c447c",
    "primary_light_color": "#e6f1fb",
    "accent_color": "#3e8ed0",
    "accent_hover_color": "#226296",
    "info_background_color": "#e6f1fb",
    "surface_color": "#ffffff",
    "muted_text_color": "#5d6572",
    "border_color": "#d3d3d3",
    "danger_color": "#f14668",
    "body_font": "open_sans",
    "heading_font": "open_sans",
    "shadow_sm": "0 1px 3px 0 rgba(0, 0, 0, 0.25)",
    "shadow_lg": "0 4px 12px rgba(0, 0, 0, 0.15)",
    "border_radius": 12,
    "box_shadow": 6,
}


def seed_climweb_theme(apps, schema_editor):
    Theme = apps.get_model("base", "Theme")
    Theme.objects.get_or_create(
        name="ClimWeb Default",
        defaults={"is_default": False, **CLIMWEB_DEFAULTS},
    )


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0047_theme_acmad_portal_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="restore_climweb_defaults",
            field=models.BooleanField(
                default=False,
                help_text="Replace this theme's colors, fonts, radius, and shadows with the original ClimWeb preset.",
                verbose_name="Restore ClimWeb defaults on save",
            ),
        ),
        migrations.RunPython(seed_climweb_theme, migrations.RunPython.noop),
    ]
