# Generated by Django 5.2.14 on 2026-09-03 09:22

import django.core.validators
import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_theme_climweb_preset'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacityBuildingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='For programme records only. Never shown on the public map.', max_length=200, verbose_name='Full name')),
                ('country', django_countries.fields.CountryField(help_text="Country of the participant's National Meteorological and Hydrological Service.", max_length=2, verbose_name='Country')),
                ('institution', models.CharField(blank=True, max_length=255, verbose_name='Institution / NMHS')),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other'), ('undisclosed', 'Prefer not to say')], default='undisclosed', max_length=20, verbose_name='Gender')),
                ('category', models.CharField(choices=[('ojt', 'On-the-job training'), ('secondment', 'Secondment')], default='ojt', max_length=20, verbose_name='Category')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, help_text='Leave empty if the engagement is still ongoing.', null=True, verbose_name='End date')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to keep the record but exclude it from published counts.', verbose_name='Include on maps')),
                ('notes', models.TextField(blank=True, verbose_name='Internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Capacity Building Participant',
                'verbose_name_plural': 'Capacity Building Participants',
                'ordering': ('-start_date', 'full_name'),
                'indexes': [models.Index(fields=['country', 'category', 'is_active'], name='base_capaci_country_12ffb7_idx')],
            },
        ),
        migrations.CreateModel(
            name='ParticipantMapSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boundary_file', models.FileField(blank=True, help_text='Optional. A GeoJSON (.geojson / .json) file or a zipped shapefile (.zip) of country polygons. Leave empty to use the built-in Africa boundaries.', null=True, upload_to='participant_map/', validators=[django.core.validators.FileExtensionValidator(['geojson', 'json', 'zip'])], verbose_name='Country boundaries file')),
                ('iso3_property', models.CharField(default='iso_a3', help_text='Name of the feature property holding the ISO-3166-1 alpha-3 country code (e.g. iso_a3, ISO_A3, ADM0_A3, gid_0).', max_length=60, verbose_name='ISO alpha-3 property')),
                ('name_property', models.CharField(blank=True, default='name', help_text='Name of the feature property holding the country name.', max_length=60, verbose_name='Country name property')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Participant map settings',
            },
        ),
    ]
