# Generated by Django 5.2.14 on 2026-09-03 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_capacitybuildingparticipant_participantmapsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantmapsettings',
            name='color_scheme',
            field=models.CharField(choices=[('amber', 'Amber'), ('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple'), ('red', 'Red'), ('teal', 'Teal'), ('grey', 'Grey')], default='amber', help_text='Sequential colour ramp used to shade countries by participant count.', max_length=20, verbose_name='Map colour scheme'),
        ),
        migrations.AddField(
            model_name='participantmapsettings',
            name='no_data_color',
            field=models.CharField(default='#e9edf0', help_text='Hex colour for countries with no participants in the current view.', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Enter a 6-digit hex colour, e.g. #e9edf0.')], verbose_name='“No participants” colour'),
        ),
    ]
