# Generated by Django 5.2.14 on 2026-09-07 10:43

import climweb.base.models.site_settings
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_participantmapsettings_color_scheme_and_more'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Show FAQ in utility navigation')),
                ('navigation_label', models.CharField(default='FAQ', max_length=30, verbose_name='Navigation label')),
                ('heading', models.CharField(default='Frequently asked questions', max_length=120, verbose_name='Panel heading')),
                ('introduction', models.TextField(blank=True, default='Quick answers to common questions about our services and information.', verbose_name='Panel introduction')),
                ('items', wagtail.fields.StreamField([('faq_item', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Question', 'max_length': 255}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'ul', 'ol', 'link', 'superscript', 'subscript', 'h2', 'h3', 'h4'], 'label': 'Answer'}), 2: ('wagtail.blocks.StructBlock', [[('question', 0), ('answer', 1)]], {})}, default=climweb.base.models.site_settings.default_faq_items, help_text='Add, edit, remove, and reorder the questions shown in the FAQ panel.', verbose_name='FAQ items')),
                ('support_link_label', models.CharField(blank=True, default='Still need help? Contact us', max_length=80, verbose_name='Support link label')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
                ('support_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Support page')),
            ],
            options={
                'verbose_name': 'FAQ settings',
            },
        ),
    ]
