# Generated by Django 5.2.14 on 2026-09-21 08:44

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_participantmapsettings_color_scheme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationsettings',
            name='rcc_main_menu',
            field=wagtail.fields.StreamField([('navigation_item', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Label'}), 1: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Page', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'label': 'External URL', 'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'label': 'Include Subpages', 'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'label': 'Large Submenu Dropdown', 'required': False}), 5: ('wagtail.blocks.BooleanBlock', (), {'label': 'Show as action button', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('label', 0), ('page', 1), ('external_url', 2), ('is_action', 5)]], {}), 7: ('wagtail.blocks.StreamBlock', [[('sub_item', 6)]], {'required': False}), 8: ('wagtail.blocks.StructBlock', [[('label', 0), ('page', 1), ('external_url', 2), ('include_subpages', 3), ('large_submenu', 4), ('sub_items', 7)]], {})}, help_text='Links shown in the main header while browsing RCC pages.', null=True, verbose_name='RCC main menu'),
        ),
    ]
