# Generated by Django 5.2.14 on 2026-09-07 11:12

import wagtail.fields
from django.db import migrations


def add_faq_to_configured_utility_navigation(apps, schema_editor):
    NavigationSettings = apps.get_model('base', 'NavigationSettings')

    for navigation in NavigationSettings.objects.all():
        links = navigation.header_utility_links
        if not links:
            # Empty settings continue to use the template's default utility links.
            continue

        raw_links = list(links.raw_data)
        has_faq = any(
            block.get('type') == 'utility_link'
            and block.get('value', {}).get('action') == 'faq'
            for block in raw_links
        )
        if has_faq:
            continue

        raw_links.append({
            'type': 'utility_link',
            'value': {
                'action': 'faq',
                'label': 'FAQ',
                'page': None,
                'external_url': '',
                'icon': '',
                'open_in_new_tab': False,
                'enabled': True,
            },
        })
        navigation.header_utility_links = raw_links
        navigation.save(update_fields=['header_utility_links'])


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_faqsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqsettings',
            name='is_enabled',
        ),
        migrations.RemoveField(
            model_name='faqsettings',
            name='navigation_label',
        ),
        migrations.AlterField(
            model_name='navigationsettings',
            name='header_utility_links',
            field=wagtail.fields.StreamField([('utility_link', 7)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('link', 'Open a page or URL'), ('faq', 'Open the FAQ drawer')], 'help_text': 'Choose FAQ drawer to add the slide-out FAQ without selecting a page.', 'label': 'Action'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Label', 'max_length': 60}), 2: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Select a page, or provide an external URL below.', 'label': 'Internal page', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'Used instead of the internal page when provided.', 'label': 'External URL', 'required': False}), 4: ('wagtailiconchooser.blocks.IconChooserBlock', (), {'label': 'Icon', 'required': False}), 5: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Open in a new tab', 'required': False}), 6: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': 'Enabled', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('action', 0), ('label', 1), ('page', 2), ('external_url', 3), ('icon', 4), ('open_in_new_tab', 5), ('enabled', 6)]], {})}, help_text='Add, reorder, enable, or disable links shown in the header utility bar.', null=True, verbose_name='Header utility links'),
        ),
        migrations.RunPython(
            add_faq_to_configured_utility_navigation,
            migrations.RunPython.noop,
        ),
    ]
