# Generated by Django 5.2.14 on 2026-09-22 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0051_navigationsettings_rcc_main_menu"),
        ("base", "0052_remove_faqsettings_is_enabled_and_more"),
    ]

    operations = []
