# Generated by Django 5.2.14 on 2026-07-20 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_alter_feedbackformfield_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackformfield',
            options={'ordering': ['sort_order']},
        ),
    ]
