# Generated by Django 5.2.14 on 2026-09-13 16:48

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
import wagtailcache.cache
import wagtailmetadata.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('banner_title', models.CharField(max_length=255, verbose_name='Banner Title')),
                ('banner_subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Banner Subtitle')),
                ('call_to_action_button_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Call to action button text')),
                ('introduction_heading', models.CharField(blank=True, default='Our governance', max_length=100, verbose_name='Introduction heading')),
                ('introduction_title', models.CharField(blank=True, default='Meet the Board of Governors', max_length=150, verbose_name='Introduction title')),
                ('introduction_text', wagtail.fields.RichTextField(blank=True, verbose_name='Introduction text')),
                ('banner_image', models.ForeignKey(blank=True, help_text='A high quality banner image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Banner Image')),
                ('call_to_action_related_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Call to action related page')),
                ('search_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Search image')),
            ],
            options={
                'verbose_name': 'Board of Governors Page',
            },
            bases=(wagtailmetadata.models.WagtailImageMetadataMixin, 'wagtailcore.page', models.Model, wagtailcache.cache.WagtailCacheMixin),
        ),
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('role', models.CharField(blank=True, help_text='For example: Governor for Ghana or Permanent Secretary.', max_length=150, verbose_name='Role or position')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('biography', wagtail.fields.RichTextField(blank=True, verbose_name='Short biography')),
                ('photo', models.ForeignKey(blank=True, help_text='A high-quality square portrait works best.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Portrait')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_members', to='board.boardpage')),
            ],
            options={
                'verbose_name': 'Board member',
                'verbose_name_plural': 'Board members',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='BoardPresidentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('banner_title', models.CharField(max_length=255, verbose_name='Banner Title')),
                ('banner_subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Banner Subtitle')),
                ('call_to_action_button_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Call to action button text')),
                ('name', models.CharField(max_length=100, verbose_name="President's name")),
                ('role', models.CharField(default='President of the Board of Governors', max_length=150, verbose_name='Title')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('biography', wagtail.fields.RichTextField(verbose_name='Biography')),
                ('vision', wagtail.fields.RichTextField(verbose_name='Vision for ACMAD')),
                ('video_url', models.URLField(blank=True, help_text='Paste a YouTube or Vimeo URL. It will be embedded on the page.', verbose_name='Video URL')),
                ('video_title', models.CharField(blank=True, default='A message from the President', max_length=150, verbose_name='Video heading')),
                ('video_caption', models.TextField(blank=True, verbose_name='Video caption')),
                ('banner_image', models.ForeignKey(blank=True, help_text='A high quality banner image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Banner Image')),
                ('call_to_action_related_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Call to action related page')),
                ('photo', models.ForeignKey(blank=True, help_text='A high-quality portrait, ideally at least 900px wide.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Portrait')),
                ('search_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Search image')),
            ],
            options={
                'verbose_name': 'Board President Page',
            },
            bases=(wagtailmetadata.models.WagtailImageMetadataMixin, 'wagtailcore.page', models.Model, wagtailcache.cache.WagtailCacheMixin),
        ),
    ]
