# Generated by Django 5.2.14 on 2026-07-14 12:59

import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.forms.models
import wagtail.fields
import wagtailcache.cache
import wagtailmetadata.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0042_productitemtype_valid_for_days'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummerSchoolApplicationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, validators=[wagtail.contrib.forms.models.validate_to_address], verbose_name='to address')),
                ('from_address', models.EmailField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('introduction_title', models.CharField(max_length=255, verbose_name='Introduction Title')),
                ('introduction_subtitle', models.TextField(blank=True, null=True, verbose_name='Introduction Subtitle')),
                ('thank_you_text', models.TextField(blank=True, null=True, verbose_name='Thank you text')),
                ('application_deadline', models.DateField(blank=True, null=True, verbose_name='Application Deadline')),
                ('validation_field', models.CharField(blank=True, default='email_address', help_text='A field on the form to check if is already submitted so as to prevent multiple submissions by one person. This is usually the email address field in snake casing format', max_length=100, verbose_name='Validation Field')),
                ('illustration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Illustration')),
                ('search_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Search image')),
            ],
            options={
                'verbose_name': 'Summer School Application Page',
            },
            bases=(wagtailmetadata.models.WagtailImageMetadataMixin, wagtail.contrib.forms.models.FormMixin, 'wagtailcore.page', models.Model, wagtailcache.cache.WagtailCacheMixin),
        ),
        migrations.CreateModel(
            name='SummerSchoolApplicationFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_form_fields', to='summer_school.summerschoolapplicationpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SummerSchoolIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro_title', models.CharField(blank=True, max_length=255, verbose_name='Introduction Title')),
                ('intro_text', wagtail.fields.RichTextField(blank=True, verbose_name='Introduction Text')),
                ('search_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Search image')),
            ],
            options={
                'verbose_name': 'Summer School Index Page',
            },
            bases=(wagtailmetadata.models.WagtailImageMetadataMixin, 'wagtailcore.page', models.Model, wagtailcache.cache.WagtailCacheMixin),
        ),
        migrations.CreateModel(
            name='SummerSchoolPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('program_tagline', models.CharField(blank=True, max_length=255, verbose_name='Program Tagline')),
                ('hero_heading', models.CharField(max_length=255, verbose_name='Hero Heading')),
                ('hero_description', wagtail.fields.RichTextField(verbose_name='Hero Description')),
                ('hero_badges', wagtail.fields.StreamField([('badge', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 60})}, verbose_name='Hero Badges')),
                ('cta_primary_text', models.CharField(blank=True, max_length=60, verbose_name='Primary CTA Text')),
                ('cta_primary_external_url', models.URLField(blank=True, help_text='If provided, the internal page link is ignored', verbose_name='Primary CTA - External URL')),
                ('cta_secondary_text', models.CharField(blank=True, max_length=60, verbose_name='Secondary CTA Text')),
                ('cta_secondary_external_url', models.URLField(blank=True, help_text='If provided, the internal page link is ignored', verbose_name='Secondary CTA - External URL')),
                ('key_info_dates', models.CharField(blank=True, max_length=255, verbose_name='Dates')),
                ('edition_start_date', models.DateField(blank=True, help_text='Used to order editions on the index page', null=True, verbose_name='Edition Start Date')),
                ('key_info_location', models.CharField(blank=True, max_length=255, verbose_name='Location')),
                ('key_info_format', models.CharField(blank=True, max_length=255, verbose_name='Format')),
                ('key_info_language', models.CharField(blank=True, max_length=255, verbose_name='Language')),
                ('key_info_certificate', models.CharField(blank=True, max_length=255, verbose_name='Certificate')),
                ('key_info_contact', models.CharField(blank=True, max_length=255, verbose_name='Contact')),
                ('apply_button_text', models.CharField(default='Apply', max_length=60, verbose_name='Apply Button Text')),
                ('background_intro', wagtail.fields.RichTextField(blank=True, verbose_name='Background Introduction')),
                ('background_items', wagtail.fields.StreamField([('card', 3)], blank=True, block_lookup={0: ('wagtailiconchooser.blocks.IconChooserBlock', (), {'label': 'Icon', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': False}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'ul', 'ol', 'link', 'superscript', 'subscript', 'h2', 'h3', 'h4']}), 3: ('wagtail.blocks.StructBlock', [[('icon', 0), ('title', 1), ('description', 2)]], {})}, verbose_name='Background Items')),
                ('structure_items', wagtail.fields.StreamField([('card', 3)], blank=True, block_lookup={0: ('wagtailiconchooser.blocks.IconChooserBlock', (), {'label': 'Icon', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': False}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'ul', 'ol', 'link', 'superscript', 'subscript', 'h2', 'h3', 'h4']}), 3: ('wagtail.blocks.StructBlock', [[('icon', 0), ('title', 1), ('description', 2)]], {})}, verbose_name='Structure Items')),
                ('trainers', wagtail.fields.StreamField([('trainer', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Name of trainer', 'max_length': 255}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Select/upload image', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Organisation working for or representing', 'max_length': 255, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Position in organisation', 'max_length': 255, 'required': False}), 4: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Short bio', 'label': 'Short bio', 'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('lead_facilitator', 'Lead Facilitator'), ('instructor', 'Instructor'), ('guest_trainer', 'Guest Trainer')], 'help_text': 'Select Role. Leave blank if normal trainer', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': "Trainer's session/module focus", 'max_length': 255, 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('name', 0), ('image', 1), ('organisation', 2), ('position', 3), ('bio', 4), ('role', 5), ('module_taught', 6)]], {})}, verbose_name='Trainers')),
                ('schedule_sessions', wagtail.fields.StreamField([('session', 11)], blank=True, block_lookup={0: ('wagtail.blocks.DateTimeBlock', (), {'help_text': 'Session Start Time'}), 1: ('wagtail.blocks.DateTimeBlock', (), {'help_text': 'Session End Time'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Session Image', 'required': False}), 3: ('wagtail.blocks.TextBlock', (), {'help_text': 'Session title'}), 4: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'ul', 'ol', 'link', 'superscript', 'subscript', 'h2', 'h3', 'h4'], 'help_text': 'Detail', 'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('foundation', 'Foundation'), ('sectoral', 'Sectoral')], 'help_text': 'Foundation or Sectoral module', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Name of person', 'label': 'Name of person', 'max_length': 255}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Select/upload image', 'required': False}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('lecturer', 'Lecturer'), ('facilitator', 'Facilitator')], 'help_text': 'Select Role', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('name', 6), ('image', 7), ('role', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('start_time', 0), ('end_time', 1), ('image', 2), ('title', 3), ('detail', 4), ('session_type', 5), ('roles', 10)]], {})}, verbose_name='Schedule Sessions')),
                ('cohorts', wagtail.fields.StreamField([('cohort', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Cohort year, e.g. 2025', 'max_length': 20}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Cohort group photo', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 20, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Training', 'max_length': 60, 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Projects', 'max_length': 60, 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Alumni', 'max_length': 60, 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'default': 'View highlights and achievements', 'max_length': 60, 'required': False}), 8: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Highlights - Internal Page', 'required': False}), 9: ('wagtail.blocks.URLBlock', (), {'help_text': 'If provided, the internal page link is ignored', 'label': 'Highlights - External URL', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('year', 0), ('location', 1), ('photo', 2), ('stat_1_value', 3), ('stat_1_label', 4), ('stat_2_value', 3), ('stat_2_label', 5), ('stat_3_value', 3), ('stat_3_label', 6), ('highlights_link_text', 7), ('highlights_page', 8), ('highlights_external_url', 9)]], {})}, verbose_name='Cohorts')),
                ('concept_note_title', models.CharField(default='Concept Note', max_length=255, verbose_name='Concept Note Title')),
                ('concept_note_description', wagtail.fields.RichTextField(blank=True, verbose_name='Concept Note Description')),
                ('concept_note_checklist', wagtail.fields.StreamField([('item', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100})}, verbose_name='Concept Note Checklist')),
                ('faq', wagtail.fields.StreamField([('faq', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'ul', 'ol', 'link', 'superscript', 'subscript', 'h2', 'h3', 'h4']}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('heading', 1), ('description', 2), ('image', 3)]], {}), 5: ('wagtail.blocks.StreamBlock', [[('collapsibles', 4)]], {}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('collapsibles', 5)]], {})}, verbose_name='FAQ')),
                ('faq_view_all_text', models.CharField(blank=True, max_length=60, verbose_name='FAQ - View All Text')),
                ('featured', models.BooleanField(default=False, help_text='Show this edition as featured ?', verbose_name='Featured')),
                ('is_hidden', models.BooleanField(default=False, help_text='Make this edition hidden in listings or elsewhere', verbose_name='Is hidden')),
                ('is_visible_on_homepage', models.BooleanField(default=False, help_text='Show this edition on the homepage ?', verbose_name='Is visible on homepage')),
                ('application_open', models.BooleanField(default=True, verbose_name='Application open')),
                ('concept_note_document', models.ForeignKey(blank=True, help_text='Downloadable concept note document, preferably in PDF format', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.customdocumentmodel', verbose_name='Concept Note Document')),
                ('concept_note_thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Concept Note Thumbnail')),
                ('cta_primary_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Primary CTA - Internal Page')),
                ('cta_secondary_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Secondary CTA - Internal Page')),
                ('decorative_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Decorative Image')),
                ('faq_view_all_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='FAQ - View All Page')),
                ('hero_background_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Hero Background Image')),
                ('search_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Search image')),
            ],
            options={
                'verbose_name': 'Summer School Page',
                'ordering': ['-edition_start_date'],
            },
            bases=(wagtailmetadata.models.WagtailImageMetadataMixin, 'wagtailcore.page', models.Model, wagtailcache.cache.WagtailCacheMixin),
        ),
    ]
