# Generated by Django 5.2.14 on 2026-07-14 15:32

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summer_school', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summerschoolindexpage',
            name='intro_text',
        ),
        migrations.RemoveField(
            model_name='summerschoolindexpage',
            name='intro_title',
        ),
        migrations.AddField(
            model_name='summerschoolindexpage',
            name='banner_description',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Banner Description'),
        ),
        migrations.AddField(
            model_name='summerschoolindexpage',
            name='banner_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Banner Heading'),
        ),
        migrations.AddField(
            model_name='summerschoolindexpage',
            name='hero_background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Hero Background Image'),
        ),
        migrations.AddField(
            model_name='summerschoolindexpage',
            name='hero_badges',
            field=wagtail.fields.StreamField([('badge', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 60})}, verbose_name='Hero Badges'),
        ),
        migrations.AddField(
            model_name='summerschoolindexpage',
            name='hero_description',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Hero Description'),
        ),
        migrations.AddField(
            model_name='summerschoolindexpage',
            name='hero_heading',
            field=models.CharField(blank=True, max_length=255, verbose_name='Hero Heading'),
        ),
        migrations.AddField(
            model_name='summerschoolindexpage',
            name='hero_subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Hero Subtitle'),
        ),
        migrations.AddField(
            model_name='summerschoolpage',
            name='card_icon',
            field=models.CharField(blank=True, help_text="Small icon shown on this edition's card on the index page", max_length=100, null=True, verbose_name='Card Icon'),
        ),
        migrations.AddField(
            model_name='summerschoolpage',
            name='status_badge_text',
            field=models.CharField(blank=True, help_text="e.g. 'Applications opening soon', 'Applications open'. Leave blank to hide the badge.", max_length=60, verbose_name='Status Badge Text'),
        ),
    ]
