# Generated by Django 5.2.14 on 2026-07-15 07:27

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summer_school', '0002_remove_summerschoolindexpage_intro_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='summerschoolpage',
            name='eligibility_criteria',
            field=wagtail.fields.StreamField([('item', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200})}, verbose_name='Eligibility Criteria'),
        ),
        migrations.AddField(
            model_name='summerschoolpage',
            name='eligibility_intro',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Eligibility Introduction'),
        ),
        migrations.AddField(
            model_name='summerschoolpage',
            name='prerequisite_courses_text',
            field=models.CharField(blank=True, default='View pre-requisite courses', max_length=150, verbose_name='Pre-requisite Courses - Link Text'),
        ),
        migrations.AddField(
            model_name='summerschoolpage',
            name='prerequisite_courses_url',
            field=models.URLField(blank=True, help_text='Link to an external course a candidate should complete before applying', verbose_name='Pre-requisite Courses - External URL'),
        ),
    ]
