# Generated by Django 5.2.14 on 2026-07-15 08:02

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summer_school', '0003_summerschoolpage_eligibility_criteria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='summerschoolapplicationpage',
            name='journey_note',
            field=models.CharField(blank=True, help_text='Optional caption shown under the journey steps', max_length=255, verbose_name='Application Journey Note'),
        ),
        migrations.AddField(
            model_name='summerschoolapplicationpage',
            name='journey_stages',
            field=wagtail.fields.StreamField([('stage', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 60})}, verbose_name='Application Journey Stages'),
        ),
        migrations.AlterField(
            model_name='summerschoolapplicationformfield',
            name='field_type',
            field=models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field'), ('image', 'Upload Image'), ('document', 'Upload PDF Document')], max_length=16, verbose_name='field type'),
        ),
    ]
