# Generated by Django 5.2.14 on 2026-07-15 08:31

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summer_school', '0004_summerschoolapplicationpage_journey_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='summerschoolpage',
            name='partners',
            field=wagtail.fields.StreamField([('partner', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Organisation name', 'max_length': 150}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Organisation logo'}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': "Link to the organisation's website", 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('sponsor', 'Sponsor'), ('organizer', 'Organizer'), ('partner', 'Partner')], 'help_text': 'Sponsor, Organizer, or Partner'}), 4: ('wagtail.blocks.StructBlock', [[('name', 0), ('logo', 1), ('website_url', 2), ('role', 3)]], {})}, verbose_name='Sponsors, Organizers & Partners'),
        ),
    ]
