# Generated by Django 5.2.14 on 2026-07-18 16:42

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summer_school', '0005_summerschoolpage_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='summerschoolpage',
            name='additional_materials',
            field=wagtail.fields.StreamField([('additional_material', 4)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('document', 'Document/File'), ('image', 'Image')]}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 2: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Select document or file', 'required': False, 'verbose_name': 'Document/File'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Select/upload image', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('type', 0), ('title', 1), ('document', 2), ('image', 3)]], {})}, null=True, verbose_name='Additional Materials'),
        ),
        migrations.AlterField(
            model_name='summerschoolpage',
            name='trainers',
            field=wagtail.fields.StreamField([('trainer', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Name of trainer', 'max_length': 255}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Select/upload image', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Organisation working for or representing', 'max_length': 255, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Position in organisation', 'max_length': 255, 'required': False}), 4: ('wagtail.blocks.RichTextBlock', (), {'help_text': "Full bio, shown in a popup when a visitor clicks the trainer's card", 'label': 'Full bio', 'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('lead_facilitator', 'Lead Facilitator'), ('instructor', 'Instructor'), ('guest_trainer', 'Guest Trainer')], 'help_text': 'Select Role. Leave blank if normal trainer', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': "Trainer's session/module focus", 'max_length': 255, 'required': False}), 7: ('wagtailiconchooser.blocks.IconChooserBlock', (), {'label': 'Icon', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. LinkedIn, Personal website, Google Scholar', 'max_length': 60, 'required': False}), 9: ('wagtail.blocks.URLBlock', (), {'help_text': 'Link URL'}), 10: ('wagtail.blocks.StructBlock', [[('icon', 7), ('text', 8), ('url', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {'help_text': 'LinkedIn, personal page, Google Scholar, etc. - each with its own icon, label and URL.', 'label': 'Links', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('name', 0), ('image', 1), ('organisation', 2), ('position', 3), ('bio', 4), ('role', 5), ('module_taught', 6), ('links', 11)]], {})}, verbose_name='Trainers'),
        ),
    ]
