# Generated by Django 5.2.14 on 2026-07-18 18:18

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summer_school', '0006_summerschoolpage_additional_materials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='summerschoolapplicationpage',
            name='enable_submission_ratings',
            field=models.BooleanField(default=False, help_text='If off, staff can only view submissions - the rating/comment section is hidden entirely from the review screen.', verbose_name='Enable ratings & comments on submissions'),
        ),
        migrations.AddField(
            model_name='summerschoolapplicationpage',
            name='notification_emails',
            field=wagtail.fields.StreamField([('email', 0)], blank=True, block_lookup={0: ('wagtail.blocks.EmailBlock', (), {'label': 'Email address'})}, help_text='Receives a weekly submission-count digest, and (if a closing date is set below) a summary the day before it closes.', verbose_name='Notification emails'),
        ),
        migrations.AddField(
            model_name='summerschoolapplicationpage',
            name='submissions_closing_date',
            field=models.DateField(blank=True, help_text='If set, a summary + link to view submissions is emailed to the notification emails above one day before this date.', null=True, verbose_name='Submissions closing date'),
        ),
    ]
