# Generated by Django 5.2.14 on 2026-07-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summer_school', '0008_remove_summerschoolapplicationpage_submissions_closing_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summerschoolapplicationformfield',
            options={},
        ),
        migrations.AddField(
            model_name='summerschoolapplicationformfield',
            name='max_length',
            field=models.PositiveIntegerField(blank=True, help_text='Only applies to the "Multi-line text" field type - leave blank for no limit.', null=True, verbose_name='Maximum characters'),
        ),
    ]
