# Generated by Django 5.2.14 on 2026-07-20 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summer_school', '0009_alter_summerschoolapplicationformfield_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summerschoolapplicationformfield',
            options={'ordering': ['sort_order']},
        ),
    ]
