# Generated by Django 5.2.14 on 2026-07-29 07:23

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summer_school', '0010_alter_summerschoolapplicationformfield_options'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='summerschoolpage',
            name='featured_image',
            field=models.ForeignKey(blank=True, help_text='Shown in the spotlight card when this edition is featured on the index page. Leave blank to use the Hero Background Image instead.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Featured Image'),
        ),
        migrations.AlterField(
            model_name='summerschoolpage',
            name='trainers',
            field=wagtail.fields.StreamField([('trainer', 13)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Name of trainer', 'max_length': 255}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Select/upload image', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Organisation working for or representing', 'max_length': 255, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Position in organisation', 'max_length': 255, 'required': False}), 4: ('wagtail.blocks.RichTextBlock', (), {'help_text': "Full bio, shown in a popup when a visitor clicks the trainer's card", 'label': 'Full bio', 'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('lead_facilitator', 'Lead Facilitator'), ('facilitator', 'Facilitator'), ('instructor', 'Instructor'), ('guest_trainer', 'Guest Trainer'), ('other', 'Other')], 'help_text': 'Select Role. Leave blank if normal trainer', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Only used when Role above is set to "Other"', 'label': 'Custom role name', 'max_length': 100, 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': "Trainer's session/module focus", 'max_length': 255, 'required': False}), 8: ('wagtailiconchooser.blocks.IconChooserBlock', (), {'label': 'Icon', 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. LinkedIn, Personal website, Google Scholar', 'max_length': 60, 'required': False}), 10: ('wagtail.blocks.URLBlock', (), {'help_text': 'Link URL'}), 11: ('wagtail.blocks.StructBlock', [[('icon', 8), ('text', 9), ('url', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'help_text': 'LinkedIn, personal page, Google Scholar, etc. - each with its own icon, label and URL.', 'label': 'Links', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('name', 0), ('image', 1), ('organisation', 2), ('position', 3), ('bio', 4), ('role', 5), ('custom_role_name', 6), ('module_taught', 7), ('links', 12)]], {})}, verbose_name='Trainers'),
        ),
    ]
