# Generated by Django 5.2.14 on 2026-07-29 08:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summer_school', '0011_summerschoolpage_featured_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='summerschoolindexpage',
            name='editions_per_page',
            field=models.PositiveIntegerField(default=6, help_text='How many editions should be visible per page in the programme listing below the spotlight?', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(20)], verbose_name='Editions per page'),
        ),
    ]
