# Generated by Django 5.2.14 on 2026-09-15 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summer_school', '0013_alter_summerschoolapplicationpage_validation_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summerschoolindexpage',
            name='editions_per_page',
            field=models.PositiveIntegerField(default=6, help_text='How many editions should be visible per page in the programme listing below the spotlight ?', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(20)], verbose_name='Editions per page'),
        ),
    ]
