# Generated by Django 5.2.14 on 2026-08-27 08:42

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex_page', '0004_alter_flexpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='content',
            field=wagtail.fields.StreamField([('title_text', 2), ('title_text_image', 4), ('accordion', 10), ('table', 12), ('met_services_directory', 16)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Section Title', 'max_length': 100, 'verbose_name': 'Section Title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'underline', 'strikethrough', 'superscript', 'subscript', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'blockquote', 'code', 'ol', 'ul', 'link', 'document-link', 'image', 'embed', 'hr', 'anchor', 'table', 'justifyLeft', 'justifyCenter', 'justifyRight', 'justifyFull', 'indent', 'outdent', 'html'], 'help_text': 'Section description', 'verbose_name': 'Section Text'}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1)]], {}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1), ('image', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'required': True}), 6: ('wagtail.blocks.CharBlock', (), {}), 7: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'ul', 'ol', 'link', 'superscript', 'subscript', 'h2', 'h3', 'h4']}), 8: ('wagtail.blocks.StructBlock', [[('heading', 6), ('description', 7), ('image', 3)]], {}), 9: ('wagtail.blocks.StreamBlock', [[('collapsibles', 8)]], {}), 10: ('wagtail.blocks.StructBlock', [[('title', 5), ('collapsibles', 9)]], {}), 11: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'table_options': {'colHeaders': False, 'rowHeaders': False}}), 12: ('wagtail.blocks.StructBlock', [[('title', 5), ('table', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'default': 'African National Meteorological Services', 'label': 'Section heading', 'max_length': 120}), 14: ('wagtail.blocks.RichTextBlock', (), {'default': 'Explore the official meteorological and hydrological services serving countries across Africa.', 'features': ['bold', 'ul', 'ol', 'link', 'superscript', 'subscript', 'h2', 'h3', 'h4'], 'label': 'Introduction', 'required': False}), 15: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'label': 'Show directory search', 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('heading', 13), ('introduction', 14), ('show_search', 15)]], {})}, null=True),
        ),
    ]
