# Generated by Django 5.2.14 on 2026-08-31 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staffpage_introduction_heading_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='LinkedIn profile'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='website',
            field=models.URLField(blank=True, verbose_name='Professional website'),
        ),
        migrations.CreateModel(
            name='StaffProfileAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_digest', models.CharField(blank=True, max_length=64)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_access', to='staff.staffmember')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile_access', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfileUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('photo_data', models.BinaryField(blank=True, default=bytes)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Awaiting review'), ('approved', 'Approved'), ('changes_requested', 'Changes requested')], default='draft', max_length=24)),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_comment', models.TextField(blank=True)),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='staff.staffprofileaccess')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_staff_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'permissions': [('review_staff_profiles', 'Can review staff profile submissions')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['draft', 'submitted'])), fields=('access',), name='staff_one_open_profile_update')],
            },
        ),
    ]
