# Generated by Django 5.2.14 on 2026-07-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_eventregistrationpage_notification_emails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventregistrationformfield',
            options={},
        ),
        migrations.AlterModelOptions(
            name='eventregistrationformtemplatefield',
            options={},
        ),
        migrations.AddField(
            model_name='eventregistrationformfield',
            name='max_length',
            field=models.PositiveIntegerField(blank=True, help_text='Only applies to the "Multi-line text" field type - leave blank for no limit.', null=True, verbose_name='Maximum characters'),
        ),
        migrations.AddField(
            model_name='eventregistrationformtemplatefield',
            name='max_length',
            field=models.PositiveIntegerField(blank=True, help_text='Only applies to the "Multi-line text" field type - leave blank for no limit.', null=True, verbose_name='Maximum characters'),
        ),
    ]
