# Generated by Django 5.2.14 on 2026-07-20 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_eventregistrationformfield_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventregistrationformfield',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='eventregistrationformtemplatefield',
            options={'ordering': ['sort_order']},
        ),
    ]
