# Generated by Django 5.2.14 on 2026-08-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_eventregistrationformfield_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistrationformtemplate',
            name='validation_field',
            field=models.CharField(default='email', max_length=200),
        ),
        migrations.AlterField(
            model_name='eventregistrationpage',
            name='validation_field',
            field=models.CharField(blank=True, default='email', help_text='A field on the form to check if is already submitted so as to prevent multiple submissions by one person. This is usually the email address field in snake casing format', max_length=100, verbose_name='Validation Field'),
        ),
    ]
