# Generated by Django 5.2.14 on 2026-09-11 11:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_eventregistrationformfield_field_type_and_more'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='attendance_mode',
            field=models.CharField(choices=[('in_person', 'In person'), ('online', 'Online'), ('hybrid', 'Hybrid')], default='in_person', max_length=20, verbose_name='Attendance mode'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='meeting_platform',
            field=models.CharField(blank=True, choices=[('zoom', 'Zoom'), ('google_meet', 'Google Meet')], default='zoom', help_text='Platform for Event', max_length=100, verbose_name='Meeting Registration Integration Platform'),
        ),
        migrations.CreateModel(
            name='EventMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_event_id', models.CharField(max_length=255, unique=True)),
                ('conference_request_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('meet_url', models.URLField(blank=True)),
                ('payload_hash', models.CharField(blank=True, max_length=64)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('last_error', models.TextField(blank=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_meeting', to='events.eventpage')),
            ],
        ),
        migrations.CreateModel(
            name='GoogleMeetSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='Enable Google Meet integration')),
                ('organizer_email', models.EmailField(blank=True, help_text='The Workspace user the service account impersonates. Meetings and calendar events are owned by this account.', max_length=254, verbose_name='Google Workspace organizer email')),
                ('calendar_id', models.CharField(blank=True, help_text="Leave blank to use the organizer's primary calendar.", max_length=255, verbose_name='Google Calendar ID')),
                ('participant_email_subject', models.CharField(blank=True, default="You're registered: {event_title}", help_text='You may use {event_title} in the subject.', max_length=255, verbose_name='Participant email subject')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Google Meet settings',
            },
        ),
        migrations.CreateModel(
            name='EventRegistrationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.PositiveBigIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_meet_deliveries', to='events.eventregistrationpage')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('registration_page', 'submission_id'), name='unique_google_meet_registration_delivery')],
            },
        ),
    ]
