# Generated by Django 5.2.14 on 2026-10-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_alter_eventpage_is_el_nino_related'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='enso_external_url',
            field=models.URLField(blank=True, help_text="Optional link to the activity on the hosting organisation's website.", max_length=1000, verbose_name='External activity URL'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='enso_host_organisation',
            field=models.CharField(blank=True, help_text='For a partner activity, enter the organisation hosting it, such as PAFO or ICPAC.', max_length=255, verbose_name='Hosting organisation'),
        ),
    ]
